// Vanguard v12 — ENCICLOPEDIA MUNDIAL: fichas enciclopedicas de guerras,
// politica, lideres, partidos y religiones. Fotos reales en /assets/wiki/.
// Cada ficha enlaza con la API de Wikipedia en vivo (src/app/api/wiki).

export type WikiCat = "GUERRAS" | "POLITICA" | "LIDERES" | "PARTIDOS" | "RELIGIONES";

export interface WikiEntry {
  id: string;
  cat: WikiCat;
  title: string;
  subtitle: string;
  dates: string;
  region: string;
  img?: string;
  stats: { label: string; value: string }[];
  desc: string;
  facts: string[];
  timeline: { year: string; text: string }[];
  wiki: string;
}

export const WIKI_CATS: { cat: WikiCat; label: string; desc: string }[] = [
  { cat: "GUERRAS", label: "Guerras", desc: "Los conflictos que redibujaron el mapa" },
  { cat: "POLITICA", label: "Politica e ideologias", desc: "Sistemas y doctrinas que gobiernan naciones" },
  { cat: "LIDERES", label: "Presidentes y lideres", desc: "Rostros reales del poder en la historia" },
  { cat: "PARTIDOS", label: "Partidos politicos", desc: "Las maquinas electorales del mundo" },
  { cat: "RELIGIONES", label: "Religiones", desc: "Fech, mapas y civilizacion" },
];

export const WIKI_ENTRIES: WikiEntry[] = [
  // ================= GUERRAS =================
  {
    id: "ww1", cat: "GUERRAS", title: "Primera Guerra Mundial", subtitle: "La Gran Guerra", dates: "1914–1918", region: "Europa, Medio Oriente, Africa, Oceanía",
    img: "/assets/wiki/war-ww1.jpg",
    stats: [{ label: "Bajas militares", value: "~9–11 millones" }, { label: "Bajas civiles", value: "~6–8 millones" }, { label: "Paises beligerantes", value: "32" }, { label: "Coste estimado", value: "~208.000 M US$ de 1914" }],
    desc: "La Primera Guerra Mundial enfrento a las Potencias Centrales (Alemania, Austria-Hungria, Imperio Otomano) contra la Triple Entente (Francia, Reino Unido, Rusia, y desde 1917 Estados Unidos). El asesinato del archiduque Francisco Fernando en Sarajevo encendio una mecha de alianzas rigidas que arrastro a todo el continente.\n\nLa guerra industrializada introdujo trincheras, ametralladoras, tanques, gas venenoso y guerra submarina. Terminó con el Tratado de Versalles, el colapso de cuatro imperios y un mapa de Europa redibujado que sembró las fracturas de la Segunda Guerra Mundial.",
    facts: ["La navidad de 1914 vio treguas espontaneas con partidos de futbol entre trincheras.", "El gas mostaza causo mas de 90.000 muertes y un millon de heridos.", "La gripe espanola de 1918 mato mas soldados que el propio frente.", "Los tanques debutaron en el Somme en 1916."],
    timeline: [{ year: "1914", text: "Atentado de Sarajevo y cascada de declaraciones de guerra" }, { year: "1916", text: "Verdun y el Somme: el desgaste industrial" }, { year: "1917", text: "Rusia se retira; EEUU entra en la guerra" }, { year: "1918", text: "Ofensiva de los Cien Dias y armisticio del 11 de noviembre" }, { year: "1919", text: "Tratado de Versalles: reparaciones y nuevas fronteras" }],
    wiki: "Primera Guerra Mundial",
  },
  {
    id: "ww2", cat: "GUERRAS", title: "Segunda Guerra Mundial", subtitle: "El conflicto total", dates: "1939–1945", region: "Global",
    img: "/assets/wiki/war-ww2.jpg",
    stats: [{ label: "Muertos totales", value: "~70–85 millones" }, { label: "Paises beligerantes", value: "57+" }, { label: "Holocausto", value: "~6 millones de victimas judias" }, { label: "Refugiados", value: "~60 millones desplazados" }],
    desc: "El conflicto mas letal de la historia opuso al Eje (Alemania nazi, Italia, Japon) a los Aliados (Reino Unido, URSS, Estados Unidos, China, Francia y decenas mas). Comenzo con la invasion de Polonia y abarco el Holocausto, la guerra relampago en Europa, el Pacifico y el desenlace nuclear.\n\nCausas profundas: humillacion de Versalles, crisis de 1929, auge de fascismos y apaciguamiento fallido. Culmino con la rendicion alemana en mayo de 1945 y japonesa en septiembre, tras las bombas de Hiroshima y Nagasaki. Fundo la ONU y un orden bipolar.",
    facts: ["El frente oriental concentro cerca de la mitad de las muertes de la guerra.", "Stalingrado (1942-43) fue la batalla mas sangrienta: ~2 millones de bajas.", "El Proyecto Manhattan costó 2.000 M US$ de la epoca.", "En 1945 gran parte del oro monetario mundial estaba en Fort Knox."],
    timeline: [{ year: "1939", text: "Invasion de Polonia; Inglaterra y Francia declaran la guerra" }, { year: "1941", text: "Barbarroja contra la URSS y Pearl Harbor: guerra global" }, { year: "1942-43", text: "Stalingrado y El Alamein: giro de la marea" }, { year: "1944", text: "Desembarco de Normandia (Dia D)" }, { year: "1945", text: "Caida de Berlin, bombas atomicas y rendicion del Japon" }],
    wiki: "Segunda Guerra Mundial",
  },
  {
    id: "fria", cat: "GUERRAS", title: "Guerra Fria", subtitle: "El duelo bipolar", dates: "1947–1991", region: "Global",
    img: "/assets/wiki/war-fria.jpg",
    stats: [{ label: "Bloques", value: "OTAN vs Pacto de Varsovia" }, { label: "Ojivas nucleares (pico 1986)", value: "~70.300" }, { label: "Guerras subsidiarias", value: "Corea, Vietnam, Afganistan, Angola..." }, { label: "Carrera espacial", value: "1957 Sputnik · 1969 Luna" }],
    desc: "La Guerra Fria fue la rivalidad geopolitica, ideologica y tecnologica entre Estados Unidos y la Union Sovietica sin choque directo entre ambas superpotencias. Se libró mediante carreras armamentistica y espacial, espionaje (CIA vs KGB), guerras subsidiarias y propaganda global.\n\nEl muro de Berlin se convirtio en su simbolo. Crisis como la de los misiles de Cuba (1962) llevaron al borde del apocalipsis nuclear. Termino con la perestroika, la caida del muro en 1989 y la disolucion sovietica en 1991.",
    facts: ["La linea roja del telefono caliente Washington-Moscu se instalo en 1963.", "El tunnel de Berlin (Operacion Gold) espiaba al Este 11 metros bajo tierra.", "En 1983 un falso informe de satelite casi desata la guerra nuclear (Petrov).", "La carrera espacial gasto mas de 25.000 M US$ solo en el programa Apolo."],
    timeline: [{ year: "1947", text: "Doctrina Truman y Plan Marshall: contencion del comunismo" }, { year: "1948", text: "Bloqueo de Berlin y puente aereo" }, { year: "1962", text: "Crisis de los misiles de Cuba" }, { year: "1989", text: "Caida del Muro de Berlin" }, { year: "1991", text: "Disolucion de la URSS: fin del bipolarismo" }],
    wiki: "Guerra Fría",
  },
  {
    id: "napoleon", cat: "GUERRAS", title: "Guerras Napoleónicas", subtitle: "El imperio que sacudió Europa", dates: "1803–1815", region: "Europa, Egipto, Rusia",
    stats: [{ label: "Muertos est.", value: "3,5–6 millones" }, { label: "Coaliciones", value: "7 contra Francia" }, { label: "Batalla clave", value: "Waterloo (1815)" }, { label: "Pico territorial", value: "~44 M de europeos bajo hegemonia francesa" }],
    desc: "Napoleon Bonaparte convirtio la Republica francesa en un imperio que domino Europa continental entre 1804 y 1814. Sus campanias modernizaron el arte militar: cuerpos de ejercito autonomos, conscripcion masiva y guerra de movimiento.\n\nEl Bloqueo Continental contra Gran Bretaña lo arrastro a la catastrofica invasion de Rusia (1812), donde el Gran Ejercito de ~600.000 hombres quedo reducido a decenas de miles. Tras la campana de los Cien Dias, Waterloo selló su caida y el Congreso de Viena rediseño un siglo de equilibrio europeo.",
    facts: ["Napoleon diseño el codigo civil frances vigente en decenas de paises.", "En Austerlitz (1805) derrotó a austriacos y rusos en su batalla maestra.", "La retirada de Rusia perdió ~400.000 hombres por frio, hambre y cosacos.", "Fue exiliado dos veces: Elba (1814) y Santa Elena (1815)."],
    timeline: [{ year: "1804", text: "Napoleon se corona Emperador de los Franceses" }, { year: "1805", text: "Trafalgar naval pierde Francia; Austerlitz terrestre triunfa" }, { year: "1812", text: "Invasion de Rusia: el punto de inflexion" }, { year: "1814", text: "Abdicacion y exilio a Elba" }, { year: "1815", text: "Cien Dias y derrota final en Waterloo" }],
    wiki: "Guerras napoleónicas",
  },
  {
    id: "vietnam", cat: "GUERRAS", title: "Guerra de Vietnam", subtitle: "La guerra en television", dates: "1955–1975", region: "Indochina",
    img: "/assets/wiki/war-vietnam.jpg",
    stats: [{ label: "Muertos est.", value: "1,5–3,5 millones" }, { label: "EEUU desplegados", value: "~2,7 M de soldados rotaron" }, { label: "Bombas lanzadas", value: "~7 M de toneladas" }, { label: "Coste EEUU", value: "~168.000 M US$" }],
    desc: "La Guerra de Vietnam enfrento al Vietnam del Norte comunista y los guerrilleros del Vietcong contra el Vietnam del Sur apoyado por Estados Unidos. Fue el teatro central de la doctrina de contencion y el conflicto mas mediatico de la historia: las imagenes del Tet y de la napalm llegaron a cada salon norteamericano.\n\nLa estrategia de desgaste fallo ante una guerra de guerrillas, la ruta Ho Chi Minh y la resistencia politica interna en EEUU. La ofensiva del Tet (1968) volteo la opinion publica y la caida de Saigon en 1975 unificó el pais bajo Hanoi.",
    facts: ["El túnel de Cu Chi tenia mas de 200 km de galerias guerrilleras.", "El Agente Naranjo afecto a ~3 M de vietnamitas y decenas de miles de veteranos.", "La draft lottery de 1969 encendio protestas universitarias masivas.", "La foto de la 'Napalm Girl' (1972) gano el Pulitzer y cambio percepciones."],
    timeline: [{ year: "1954", text: "Dien Bien Phu: Francia abandona Indochina; pais dividido" }, { year: "1964", text: "Incidente del Golfo de Tonkin: escalada EEUU" }, { year: "1968", text: "Ofensiva del Tet: giro politico y mediatico" }, { year: "1973", text: "Acuerdos de Paris: retiro norteamericano" }, { year: "1975", text: "Caida de Saigon: reunificacion comunista" }],
    wiki: "Guerra de Vietnam",
  },
  {
    id: "cruzadas", cat: "GUERRAS", title: "Las Cruzadas", subtitle: "Guerras santas medievales", dates: "1095–1291", region: "Levante, Baltico, Iberia",
    stats: [{ label: "Expediciones mayores", value: "8–9" }, { label: "Jerusalen cristiana", value: "1099–1187" }, { label: "Estados cruzados", value: "4: Edesa, Antioquia, Tripoli, Jerusalen" }, { label: "Duracion total", value: "~200 años" }],
    desc: "Las Cruzadas fueron expediciones militares de inspiracion religiosa convocadas por el papado, con Jerusalen y los Santos Lugares como objetivo central. Mezclaban peregrinacion armada, ambicion feudal, comercio y tensiones entre cristianismo latino e islam.\n\nLa Primera Cruzada capturo Jerusalen en 1099 con enorme sangria. Saladino la reconquisto en 1187 tras Hattin. La Cuarta Cruzada se desvio y saqueo Constantinopla en 1204, debilitando alBizancio de forma irreversible. Acre, el ultimo bastion, cayo en 1291.",
    facts: ["Los cruzados llevaban la cruz cosida en la ropa: 'crucesignati'.", "Las ordenes militares (Templarios, Hospitalarios) nacieron de estas guerras.", "La Cuarta Cruzada saqueo una ciudad cristiana: Constantinopla.", "Saladino y Ricardo Corazon de Leon se convirtieron en leyendas rivales."],
    timeline: [{ year: "1095", text: "Concilio de Clermont: Urbano II convoca la cruzada" }, { year: "1099", text: "Toma de Jerusalen y fundacion de estados cruzados" }, { year: "1187", text: "Hattin y reconquista de Jerusalen por Saladino" }, { year: "1204", text: "Saqueo de Constantinopla en la Cuarta Cruzada" }, { year: "1291", text: "Caida de Acre: fin de los estados cruzados" }],
    wiki: "Cruzadas",
  },
  {
    id: "treinta", cat: "GUERRAS", title: "Guerra de los Treinta Años", subtitle: "Religion y equilibrio europeo", dates: "1618–1648", region: "Sacramento Imperio, Europa central",
    stats: [{ label: "Muertos en el Sacro Imperio", value: "25–40% de la poblacion" }, { label: "Fases", value: "Bohemia, Danesa, Sueca, Francesa" }, { label: "Batalla decisiva", value: "Breitenfeld (1631)" }, { label: "Paz", value: "Westfalia (1648)" }],
    desc: "La Guerra de los Treinta Años comenzo como conflicto religioso entre catolicos y protestantes dentro del Sacro Imperio y degenero en guerra europea general entre la casa de Habsburgo y una coalicion franco-sueco-alemana. Devastó Alemania central: algunas regiones perdieron mas de la mitad de su poblacion.\n\nLa Paz de Westfalia (1648) consagro la soberania estatal, el principio cuius regio eius religio ampliado y un nuevo orden diplomatico considerado el origen del sistema internacional moderno.",
    facts: ["La defenestracion de Praga (1618) fue la chispa: nobles lanzados por una ventana.", "El sueco Gustavo Adolfo revoluciono la artilleria movil y las lineas de fuego.", "Magdeburgo perdio ~20.000 de 25.000 habitantes en el saco de 1631.", "Westfalia consagro Suiza y Holanda como estados soberanos."],
    timeline: [{ year: "1618", text: "Defenestracion de Praga: revuelta boemia" }, { year: "1630", text: "Entrada de Suecia con Gustavo Adolfo" }, { year: "1635", text: "Francia catolica entra contra los Habsburgo" }, { year: "1648", text: "Paz de Westfalia: nace el Estado soberano" }],
    wiki: "Guerra de los Treinta Años",
  },
  {
    id: "gce", cat: "GUERRAS", title: "Guerra Civil Española", subtitle: "Ensayo general del siglo XX", dates: "1936–1939", region: "España",
    stats: [{ label: "Muertos en combate", value: "~150.000–200.000" }, { label: "Represion posterior", value: "~150.000+" }, { label: "Exiliados", value: "~450.000" }, { label: "Brigadas Internacionales", value: "~35.000 voluntarios de 50+ paises" }],
    desc: "El golpe militar de julio de 1936 contra la Segunda Republica derivo en una guerra de tres anos entre nacionalistas liderados por Franco y republicanos. Fue el campo de pruebas de las potencias: la Alemania nazi y la Italia fascista armaron a Franco; la URSS apoyo a la Republica, mientras las democracias se abstuvieron.\n\nGuernica (1937) simbolizo el bombardeo de civiles que anticipaba la Segunda Guerra Mundial. La victoria franquista en 1939 abrio una dictadura de casi cuatro decadas.",
    facts: ["El bombardeo de Guernica inspiro el cuadro de Picasso.", "La batalla del Ebro fue la mayor de la guerra: ~300.000 efectivos.", "George Orwell y Hemingway combatieron o cubrieron el frente.", "'No pasaran' se convirtió en consigna global antifascista."],
    timeline: [{ year: "1936", text: "Golpe de Estado y division del pais" }, { year: "1937", text: "Guernica; cae el Norte republicano" }, { year: "1938", text: "Batalla del Ebro: ultima gran ofensiva republicana" }, { year: "1939", text: "Caida de Madrid y fin de la guerra" }],
    wiki: "Guerra civil española",
  },
  {
    id: "golfo", cat: "GUERRAS", title: "Guerra del Golfo", subtitle: "Tormenta del Desierto", dates: "1990–1991", region: "Kuwait, Irak",
    stats: [{ label: "Coalicion", value: "35 paises liderados por EEUU" }, { label: "Duracion", value: "42 dias de campana aerea" }, { label: "Bajas coalicion", value: "~292" }, { label: "Primera TV en directo", value: "CNN y camaras inteligentes" }],
    desc: "Irak de Saddam Hussein invadio Kuwait en agosto de 1990 amenazando el 20% del petroleo mundial. Una coalicion internacional autorizada por la ONU lanzo la Operacion Tormenta del Desierto en enero de 1991: 42 dias de campana aerea y 100 horas terrestres que liberaron Kuwait.\n\nFue la primera guerra televisada en directo y el escaparate de la guerra high-tech: furtivos F-117, misiles Tomahawk y precision GPS que presagiaban el nuevo modo de combate occidental.",
    facts: ["Los F-117 furtivos abrieron el fuego sin ser detectados por el radar iraqui.", "Los misiles 'scud' hicieron sonar las alarmas antiaereas de Tel Aviv durante semanas.", "La 'muerte de la autopista' generó debate sobre violencia televisada.", "El petroleo quemado tiñó de negro el cielo del Golfo durante meses."],
    timeline: [{ year: "1990", text: "Invasion iraqui de Kuwait (2 de agosto)" }, { year: "1990", text: "Resolucion 678 de la ONU: ultimatum internacional" }, { year: "1991", text: "Tormenta del Desierto: campana aerea masiva" }, { year: "1991", text: "100 horas terrestres y liberacion de Kuwait" }],
    wiki: "Guerra del Golfo",
  },
  // ================= POLITICA =================
  {
    id: "capitalismo", cat: "POLITICA", title: "Capitalismo", subtitle: "Mercado y propiedad privada", dates: "Desde el s. XVI–XVIII", region: "Global",
    stats: [{ label: "Teoricos clave", value: "Adam Smith, Ricardo, Hayek" }, { label: "Pilar", value: "Mercado y propiedad privada" }, { label: "Crisis emblematica", value: "1929 y 2008" }, { label: "Variantes", value: "Liberal, social de mercado, dirigista" }],
    desc: "El capitalismo es el sistema economico basado en la propiedad privada de los medios de produccion, la busqueda de beneficio y la asignacion de recursos mediante mercados. Nacio con el comercio atlantico y la Revolucion Industrial, y fue teorizado por Adam Smith en 'La riqueza de las naciones' (1776): la mano invisible de los precios coordinaria el interes individual.\n\nHa evolucionado del laissez-faire del siglo XIX al Estado de bienestar keynesiano pos-1929, al neoliberalismo de los 80 y al capitalismo de plataformas digital. Sus criticos senalan desigualdad y ciclos de crisis; sus defensores, crecimiento e innovacion sin precedentes.",
    facts: ["La bolsa de Amsterdam (1602) fue el primer mercado de acciones moderno.", "El PIB mundial se multiplico por mas de 100 desde 1820.", "El 1% mas rico posee cerca de la mitad de la riqueza global.", "La palabra 'economista' popularizo a Smith como 'la ciencia del legislador'."],
    timeline: [{ year: "1776", text: "Adam Smith publica La riqueza de las naciones" }, { year: "1848", text: "Marx y Engels critican el sistema en el Manifiesto Comunista" }, { year: "1929", text: "Gran Depression: el Estado keynesiano entra en escena" }, { year: "1980", text: "Reagan-Thatcher: giro neoliberal global" }, { year: "2008", text: "Crisis financiera: debate sobre regulacion renace" }],
    wiki: "Capitalismo",
  },
  {
    id: "comunismo", cat: "POLITICA", title: "Comunismo", subtitle: "Propiedad colectiva y plan", dates: "Desde 1848", region: "Global",
    stats: [{ label: "Teoricos", value: "Marx, Engels, Lenin" }, { label: "Texto fundacional", value: "Manifiesto Comunista (1848)" }, { label: "Pico historico", value: "1/3 de la humanidad en estados comunistas (1980)" }, { label: "Practica", value: "Planificacion central y partido unico" }],
    desc: "El comunismo teorico de Marx postula una sociedad sin clases ni propiedad privada de los medios de produccion, alcanzada tras la revolucion del proletariado. La practica historica la encarno la URSS de Lenin y Stalin: planificacion central, colectivizacion y partido unico.\n\nEl modelo se extendió a China, Europa del Este, Cuba y Vietnam, compitiendo con el capitalismo en la Guerra Fria. Las carencias de incentivos y libertades, junto a hambrunas y purgas, marcaron su balance; China y Vietnam lo reformaron con mercados regulados manteniendo el partido unico.",
    facts: ["El Manifiesto Comunista abre con 'un fantasma recorre Europa'.", "El Plan Quinquenal sovietico industrializo la URSS en una decada.", "El muro de Berlin simbolizo el frente entre ambos sistemas.", "China combinó partido comunista con capitalismo de mercado desde 1978."],
    timeline: [{ year: "1848", text: "Manifiesto Comunista de Marx y Engels" }, { year: "1917", text: "Revolucion de Octubre: primer estado obrero" }, { year: "1949", text: "Victoria comunista en China" }, { year: "1991", text: "Disolucion de la URSS" }, { year: "Hoy", text: "China, Vietnam, Cuba y Laos mantienen partidos comunistas" }],
    wiki: "Comunismo",
  },
  {
    id: "fascismo", cat: "POLITICA", title: "Fascismo", subtitle: "El ultranacionalismo de entreguerras", dates: "1919–1945 (apogeo)", region: "Europa",
    stats: [{ label: "Origen", value: "Italia, 1919 (fasci di combattimento)" }, { label: "Lideres", value: "Mussolini, Hitler" }, { label: "Sello", value: "Partido unico, culto al jefe, militarismo" }, { label: "Derrota", value: "1945" }],
    desc: "El fascismo fue la ideologia ultranacionalista de entreguerras: Estado totalitario, culto al lider, militarizacion de la sociedad y enemigos interiores (comunistas, minorias). Nacio en la Italia de posguerra con Mussolini (1922, marcha sobre Roma) y su variante alemana, el nazismo, llevo a Hitler al poder en 1933.\n\nSu expansion agresiva desato la Segunda Guerra Mundial y el Holocausto. Derrotado en 1945, quedo prohibido en la mayoria de constituciones europeas como doctrina antidemocratica, aunque el termino designa todo regimen autoritario de masas.",
    facts: ["El fascio (haz de varas con hacha) era el simbolo romano del poder unido.", "Mussolini hizo correr los trenes puntual como propaganda nacional.", "Las leyes de Nuremberg (1935) institucionalizaron el racismo nazi.", "La marcha sobre Roma de 1922 forzó el gobierno con 30.000 camisas negras."],
    timeline: [{ year: "1919", text: "Mussolini funda los fasci italianos de combate" }, { year: "1922", text: "Marcha sobre Roma: Mussolini primer ministro" }, { year: "1933", text: "Hitler canciller: nazismo en el poder" }, { year: "1939-45", text: "Expansion belica y Holocausto" }, { year: "1945", text: "Derrota total del fascismo europeo" }],
    wiki: "Fascismo",
  },
  {
    id: "socialdemocracia", cat: "POLITICA", title: "Socialdemocracia", subtitle: "Capitalismo con red social", dates: "Desde 1869", region: "Norte de Europa",
    stats: [{ label: "Cuna", value: "Alemania (SPD, 1869) y Escandinavia" }, { label: "Modelo", value: "Estado de bienestar universal" }, { label: "Impuestos tipicos", value: "40–50% del PIB" }, { label: "Ejemplo", value: "Modelo nordico: Dinamarca, Suecia, Noruega" }],
    desc: "La socialdemocracia es la corriente que busca humanizar el capitalismo mediante democracia plena, Estado de bienestar, negociacion colectiva y redistribucion fiscal, renunciando a la revolucion. Nacio del marxismo reformista de Bernstein y gano su forma clasica en Escandinavia.\n\nLos modelos nordicos combinan mercados abiertos con sanidad, educacion y pensiones universales, salarios de compresion y tasas sindicales altas. Suelen liderar indices de felicidad, igualdad y confianza institucional, y exportan el debate sobre sostenibilidad fiscal.",
    facts: ["Dinamarca lidera rankings de movilidad social y flexiseguridad laboral.", "En Suecia los sindicatos cubren ~70% de los asalariados.", "El 'modelo nordico' financia bienestar con impuestos medios muy altos.", "La SPD alemana es el partido mas antiguo de Alemania."],
    timeline: [{ year: "1869", text: "Fundacion del SPD aleman" }, { year: "1932-76", text: "Suecia socialdemocrata ininterrumpida por 44 anos" }, { year: "1950-70", text: "Edad de oro del Estado de bienestar nordico" }, { year: "Hoy", text: "El modelo nordico como referencia global de igualdad" }],
    wiki: "Socialdemocracia",
  },
  {
    id: "democracia", cat: "POLITICA", title: "Democracia", subtitle: "El gobierno de la mayoría", dates: "Atenas s. V a.C. → hoy", region: "Global",
    stats: [{ label: "Regimen directo original", value: "Atenas, ~508 a.C." }, { label: "Sufragio universal 1a vez", value: "Nueva Zelanda 1893" }, { label: "Democracias hoy", value: "~90 paises plenas (varios indices)" }, { label: "Pilares", value: "Elecciones libres, division de poderes, libertades" }],
    desc: "La democracia es el sistema en el que el poder emana del pueblo mediante elecciones libres, sufragio universal, division de poderes y garantias de libertades civiles. Su cuna documental es la Atenas clasica (ekklesia y sorteo), aunque excluyera mujeres y esclavos.\n\nLa version moderna nace con las revoluciones americana y francesa, el constitucionalismo y la expansion gradual del sufragio hasta las mujeres y colonias. Hoy convive con retos: populismos, desinformacion digital y regresiones autoritarias que los indices miden cada ano.",
    facts: ["En Atenas muchos cargos se elegian por sorteo, no por voto.", "Nueva Zelanda fue el primer pais con voto femenino (1893).", "La palabra 'idiot' venia del griego: el que no participaba en politika.", "India es la mayor democracia del mundo: ~970 M de votantes habilitados."],
    timeline: [{ year: "508 a.C.", text: "Reformas de Clístenes: democracia ateniense" }, { year: "1215", text: "Carta Magna: el rey tambien obedece leyes" }, { year: "1789", text: "Declaracion de Derechos del Hombre y del Ciudadano" }, { year: "1893", text: "Primer sufragio universal femenino (NZ)" }, { year: "1948", text: "Declaracion Universal de Derechos Humanos" }],
    wiki: "Democracia",
  },
  {
    id: "monarquia", cat: "POLITICA", title: "Monarquia", subtitle: "De derecho divino a parlamentaria", dates: "Antigüedad → hoy", region: "Global",
    stats: [{ label: "Monarquias vigentes", value: "43 estados soberanos" }, { label: "Parlamentarias", value: "~15 (UK, España, Japon...)" }, { label: "Absolutas hoy", value: "Arabia Saudi, Brunei, Oman, Vatican" }, { label: "Mas antigua", value: "Japon (dinastia continua milenaria)" }],
    desc: "La monarquia es la forma de gobierno en que el jefe de Estado es vitalicio y hereditario. Durante siglos se justifico por derecho divino; las revoluciones inglesa, americana y francesa la recortaron o abolieron. Hoy la mayoria son parlamentarias: el rey reina pero no gobierna, y el poder reside en parlamentos electos.\n\nSobreviven 43 monarquias, de las absolutas del Golfo a las ceremoniales escandinavas. La britanica ha sido espejo global: de imperio a commonwealth, con una familia real que combina tradicion, soft power y controversia mediatica.",
    facts: ["La corona britanica es propietaria legal de cisnes, delfines y esturiones del reino.", "Japon tiene la dinastia continua mas antigua del planeta.", "Suecia y España fueron dictaduras que regresaron a monarquia parlamentaria.", "El microestado de Vatican es la unica monarquia electa y absoluta de Europa."],
    timeline: [{ year: "1215", text: "Carta Magna limita al monarca ingles" }, { year: "1649", text: "Decapitacion de Carlos I: la republica de Cromwell" }, { year: "1688", text: "Gloriosa Revolucion: soberania parlamentaria" }, { year: "1975", text: "España: restauracion de la monarquia democratica" }],
    wiki: "Monarquía",
  },
  {
    id: "dictadura", cat: "POLITICA", title: "Dictadura", subtitle: "El poder sin contrapesos", dates: "Todas las épocas", region: "Global",
    stats: [{ label: "Tipos", value: "Militar, de partido unico, personalista" }, { label: "Metodo clasico", value: "Golpe de Estado" }, { label: "Duracion media", value: "~9–15 anos" }, { label: "Herramientas", value: "Censura, represion, propaganda" }],
    desc: "La dictadura concentra el poder en un lider, junta o partido sin mecanismos de rendicion de cuentas: elecciones sin alternativas reales, justicia sometida, prensa censurada y oposicion reprimida. Puede llegar por golpe militar, revolucion o erosion democratica.\n\nEl siglo XX vio dictaduras de izquierda y derecha: de Franco y Pinochet a Stalin y Mao. Las transiciones hacia democracia (España 1978, America Latina en los 80, Europa del Este en 1991) muestran tanto el papel de la movilizacion social como el de las elites que negocian su salida.",
    facts: ["La palabra viene del 'dictador' romano: magistratura temporal de 6 meses.", "El PRI mexicano gobernó 71 anos seguidos sin perder una eleccion presidencial.", "Muchas dictaduras celebran 'elecciones' con un solo candidato.", "Los index de democracia (EIU, V-Dem) rastrean regresiones anuales."],
    timeline: [{ year: "1922", text: "Mussolini: primera dictadura fascista moderna" }, { year: "1930-70", text: "Ondas de golpes militares en America Latina" }, { year: "1975", text: "Muerte de Franco: transicion española" }, { year: "1991", text: "Caida del bloque sovietico" }],
    wiki: "Dictadura",
  },
  {
    id: "nacionalismo", cat: "POLITICA", title: "Nacionalismo", subtitle: "La nacion como comunidad politica", dates: "s. XVIII → hoy", region: "Global",
    stats: [{ label: "Origen moderno", value: "Revolucion Francesa y romanticismo" }, { label: "Ideologos", value: "Herder, Fichte, Mazzini" }, { label: "Versiones", value: "Civica, etnica, expansionista" }, { label: "Pico", value: "Descolonizacion (1945-1975): +100 estados" }],
    desc: "El nacionalismo sostiene que cada nacion —una comunidad con lengua, historia o cultura compartida— merece un Estado propio. Nacio moderno con la Revolucion Francesa ('la nacion soberana') y el romanticismo aleman, y reorganizo Europa en los siglos XIX y XX: unificaciones de Italia y Alemania, desenlace de imperios y dos guerras mundiales.\n\nTras 1945 impulsó la descolonizacion y hoy reaparece como populismo identitario, regionalismos y disputas de memoria. Es fuerza liberadora y destructiva a la vez: creó democracias y tambien expulsion etnicas.",
    facts: ["La 'Volkgeist' de Herder afirmaba que cada pueblo tiene un alma propia.", "El himno mas antiguo es el de Japon (Kimi ga Yo, s. IX-X).", "El nacionalismo descolono Africa: 1960 alone trajo 17 nuevos paises.", "Las olimpiadas modernas nacieron para canalizar patriotismo sin guerra."],
    timeline: [{ year: "1789", text: "Soberania nacional en la Revolucion Francesa" }, { year: "1871", text: "Unificacion de Alemania y de Italia consumada" }, { year: "1919", text: "Autodeterminacion de los pueblos (14 puntos de Wilson)" }, { year: "1960", text: "Onda de independencias africanas" }],
    wiki: "Nacionalismo",
  },
  // ================= LIDERES (fotos reales) =================
  {
    id: "fdr", cat: "LIDERES", title: "Franklin D. Roosevelt", subtitle: "El New Deal y la era atomico", dates: "1882–1945 · Presidente 1933–1945", region: "Estados Unidos",
    img: "/assets/wiki/leader-fdr.jpg",
    stats: [{ label: "Mandatos", value: "4 (unico presidente con 4)" }, { label: "Sello", value: "New Deal · Segunda Guerra Mundial" }, { label: "Partido", value: "Democrata" }, { label: "Discapacidad", value: "Paraplejia por polio desde 1921" }],
    desc: "Roosevelt guio a Estados Unidos en sus dos peores crisis del siglo XX: la Gran Depresion y la Segunda Guerra Mundial. Su New Deal creo el Estado de bienestar americano: Seguridad Social, obras publicas masivas y regulacion financiera que redefinió el papel del gobierno.\n\nElecto cuatro veces, lidero la coalicion antifascista con Churchill y Stalin, diseño la ONU y murio en el cargo en abril de 1945, semanas antes de la victoria. Su discapacidad oculta y su 'conversaciones al fuego' radiofonicas lo hicieron un mito de comunicacion politica.",
    facts: ["Sus 'fireside chats' radiofonicos crearon intimidad politica de masas.", "Fue el unico presidente electo 4 veces; luego se limito a 2 por ley.", "La frase 'solo tenemos que temer al propio temor' abrio su 1er mandato.", "Impulso la ONU desde 1942; murio antes de su primer congreso."],
    timeline: [{ year: "1933", text: "Primer mandato: New Deal contra la Depresion" }, { year: "1936", text: "Reeleccion arrolladora (46 estados)" }, { year: "1941", text: "Pearl Harbor: EEUU entra en la guerra" }, { year: "1945", text: "Muere en el cargo; Truman hereda la era nuclear" }],
    wiki: "Franklin D. Roosevelt",
  },
  {
    id: "churchill", cat: "LIDERES", title: "Winston Churchill", subtitle: "La voz de Gran Bretaña", dates: "1874–1965 · Primer ministro 1940–45, 1951–55", region: "Reino Unido",
    img: "/assets/wiki/leader-churchill.jpg",
    stats: [{ label: "Premios", value: "Nobel de Literatura (1953)" }, { label: "Frase inmortal", value: "'Sangre, esfuerzo, lagrimas y sudor'" }, { label: "Rol", value: "PM de guerra · artifice de la alianza con EEUU y URSS" }, { label: "Controversia", value: "Bengala 1943, colonialismo" }],
    desc: "Primer ministro durante la hora mas oscura de Gran Bretaña, Churchill rechazo negociar con Hitler en 1940 y convirtio su oratoria en arma de guerra. Su alianza con Roosevelt y Stalin —la 'Gran Alianza'— coordino la estrategia que derrotó al Eje.\n\nCarrera de 60 anos: soldado, periodista, politico voluble que cruzo partidos, primer ministro de guerra, derrotado en 1945 y devuelto al poder en 1951. Fue tambien un colonialista duro y responsable de decisiones discutidas como la hambruna de Bengala. Su discurso en Fulton (1946) nombró el 'telon de acero'.",
    facts: ["Gano el Nobel de Literatura por sus memorias e historia.", "A los 65 anos dirigio la guerra; vivio hasta los 90.", "Fue pintor aficionado: dejo mas de 500 cuadros.", "En 1940 le ofrecio a Francia una union anglo-francesa indestructible."],
    timeline: [{ year: "1940", text: "Se convierte en PM con la caida de Francia" }, { year: "1940", text: "Batalla de Inglaterra: 'nunca tantos debieron tanto a tan pocos'" }, { year: "1945", text: "Pierde las elecciones pese a ganar la guerra" }, { year: "1946", text: "Discurso del 'telon de acero' en Fulton" }, { year: "1951", text: "Vuelve a primer ministro" }],
    wiki: "Winston Churchill",
  },
  {
    id: "stalin", cat: "LIDERES", title: "José Stalin", subtitle: "El hombre de acero", dates: "1878–1953 · Líder soviético 1924–1953", region: "URSS",
    img: "/assets/wiki/leader-stalin.jpg",
    stats: [{ label: "Goberno", value: "29 anos la URSS" }, { label: "Industrializacion", value: "De pais agrario a superpotencia en 2 decadas" }, { label: "Represion", value: "Purgas, gulag: millones de victimas" }, { label: "Guerra", value: "Gano la Gran Guerra Patriotica" }],
    desc: "Stalin convirtio la URSS en superpotencia mediante planificacion brutal: colectivizacion forzosa, planes quinquenales y terror de Estado. Las hambrunas (Ucrania 1932-33) y la Gran Purga (1936-38) costaron millones de vidas; el gulag se volvio simbolo del sistema.\n\nEn la Segunda Guerra Mundial lidero la resistencia que derrotó a la Alemania nazi en Stalingrado y Berlín, al precio de ~27 millones de muertos sovieticos. Salio de 1945 con medio Europa bajo control comunista, inaugurando la Guerra Fria hasta su muerte en 1953.",
    facts: ["'Stalin' es un seudonimo: nacio Ioseb Besarionis dze Jughashvili.", "Su hija Svetlana desertó a EEUU en 1967.", "La Ofensiva de Berlín la supervisiono desde el Kremlin por telefono.", "Nikita Khrushchev denuncio su 'culto a la personalidad' en 1956."],
    timeline: [{ year: "1924", text: "Consolida el poder tras la muerte de Lenin" }, { year: "1932-33", text: "Hambruna del Holodomor en Ucrania" }, { year: "1936-38", text: "Gran Purga: ejercito y partido decapitados" }, { year: "1941-45", text: "Gran Guerra Patriotica contra el Eje" }, { year: "1953", text: "Muere en Moscú; de-Kalinizacion posterior" }],
    wiki: "Iósif Stalin",
  },
  {
    id: "degaulle", cat: "LIDERES", title: "Charles de Gaulle", subtitle: "El honor de Francia", dates: "1890–1970 · Presidente 1959–1969", region: "Francia",
    img: "/assets/wiki/leader-degaulle.jpg",
    stats: [{ label: "Fundacion", value: "Francia Libre (1940)" }, { label: "Frase", value: "'Francia ha perdido una batalla, no la guerra'" }, { label: "República", value: "Fundó la V República (1958)" }, { label: "Política", value: "Fuerza nuclear francesa · salida del mando OTAN" }],
    desc: "General y hombre de Estado, de Gaulle encarnó la resistencia francesa desde Londres tras la derrota de 1940: su apelación del 18 de junio llamo a seguir combatiendo. Lideró la Francia Libre, presidió el gobierno provisional y se retiro en 1946, para volver en 1958 ante la crisis argelina.\n\nFundó la V República con una presidencia fuerte, dotó a Francia de disuasion nuclear y practico una política de grandeza independiente: reconocimiento de China, salida del mando integrado de la OTAN y 'Vive le Quebec libre'.",
    facts: ["Sobrevivió a varios atentados, incluido el de Petit-Clamart (1962).", "Rechazó el armisticio por radio cuando casi nadie lo escuchaba.", "Reconoció la República Popular China en 1964, antes que EEUU.", "Renunció en 1969 tras perder un referéndum, y murio al año siguiente."],
    timeline: [{ year: "1940", text: "Apelación del 18 de junio desde Londres" }, { year: "1944", text: "Libera Paris; gobierno provisional" }, { year: "1958", text: "Vuelve al poder: V República" }, { year: "1962", text: "Independencia de Argelia" }, { year: "1969", text: "Renuncia y retiro definitivo" }],
    wiki: "Charles de Gaulle",
  },
  {
    id: "mao", cat: "LIDERES", title: "Mao Zedong", subtitle: "El Gran Timonel", dates: "1893–1976 · Líder chino 1949–1976", region: "China",
    img: "/assets/wiki/leader-mao.jpg",
    stats: [{ label: "Goberno", value: "27 anos la China comunista" }, { label: "Revolucion", value: "Victoria en 1949 tras 22 anos de guerra" }, { label: "Gran Salto", value: "Hambruna: 15–45 M de muertos (1959-61)" }, { label: "Culto", value: "Libro Rojo: 1.000 M de ejemplares" }],
    desc: "Mao unifico China bajo el Partido Comunista en 1949 tras decadas de guerra civil y resistencia japonesa. Sus campanas —colectivizacion, Gran Salto Adelante, Revolucion Cultural— transformaron al pais con costes humanes desmesurados: la hambruna del Gran Salto es la mayor de la historia.\n\nPuso a China en el mapa geopolitico (bomba atomica 1964, ONU 1971, apertura a Nixon 1972). Su culto a la personalidad fue total; tras su muerte, Deng Xiaoping reformo la economia manteniendo el sistema de partido unico.",
    facts: ["El Libro Rojo de citas fue obligatorio durante la Revolucion Cultural.", "Nado el rio Yangtze a los 72 anos como demostracion de vigor.", "Los guardias rojos persiguieron 'cuatro viejadas' y destruyeron patrimonio.", "Nixon lo llamo 'el hombre que cambio el mundo'; Mao: 'solo cambie Pekin'."],
    timeline: [{ year: "1949", text: "Proclama la Republica Popular China" }, { year: "1958", text: "Gran Salto Adelante: comunas y acereras rurales" }, { year: "1959-61", text: "Hambruna gigantesca" }, { year: "1966", text: "Revolucion Cultural: decada de caos ideologico" }, { year: "1972", text: "Recibe a Nixon: China abre al mundo" }],
    wiki: "Mao Zedong",
  },
  {
    id: "kennedy", cat: "LIDERES", title: "John F. Kennedy", subtitle: "Camelot y la era espacial", dates: "1917–1963 · Presidente 1961–1963", region: "Estados Unidos",
    img: "/assets/wiki/leader-kennedy.jpg",
    stats: [{ label: "Edad al tomar posesion", value: "43 (el 2o mas joven electo)" }, { label: "Crisis maestra", value: "Misiles de Cuba (1962)" }, { label: "Hito", value: "Meta: llegar a la Luna antes de 1970" }, { label: "Fin", value: "Asesinado en Dallas (22 nov 1963)" }],
    desc: "Kennedy simbolizo el optimismo generacional: el primer presidente catolico, joven, mediatico, con una familia real Americana (Camelot). Lidiò con la Bahía de Cochinos, el muro de Berlín y la crisis de los misiles de Cuba, donde su contención evitó la guerra nuclear.\n\nLanzó la carrera espacial ('elegimos ir a la Luna'), creo los Peace Corps y firmo el tratado de prohibicion de pruebas atomicas atmosfericas. Su asesinato en Dallas sigue generando teorias y marcó un trauma nacional; su hermano Robert murio igualmente asesinado en 1968.",
    facts: ["Gano el debate TV contra Nixon en 1960: la imagen hizo la diferencia.", "Durante la crisis de Cuba toleró 13 dias de alta tension nuclear.", "Prometió la Luna 'no porque sea facil, sino porque es dificil'.", "Su frase 'no preguntes que puede hacer America por ti' es clasica."],
    timeline: [{ year: "1961", text: "Invasion fallida de Bahia de Cochinos" }, { year: "1961", text: "Anuncia la meta de llegar a la Luna" }, { year: "1962", text: "Crisis de los misiles de Cuba" }, { year: "1963", text: "Discurso en Berlin: 'Ich bin ein Berliner'" }, { year: "1963", text: "Asesinato en Dallas" }],
    wiki: "John F. Kennedy",
  },
  {
    id: "reagan", cat: "LIDERES", title: "Ronald Reagan", subtitle: "El comunicador que ganó la Guerra Fría", dates: "1911–2004 · Presidente 1981–1989", region: "Estados Unidos",
    img: "/assets/wiki/leader-reagan.jpg",
    stats: [{ label: "Antes politico", value: "Actor y presidente del sindicato de actores" }, { label: "Doctrina", value: "Reaganomics: recortes fiscales y presión militar" }, { label: "SDI", value: "'Guerra de las galaxias'" }, { label: "Frase", value: "'Sr. Gorbachov, derribe este muro'" }],
    desc: "Reagan paso de actor de Hollywood a gobernador de California y presidente en dos mandatos arrolladores. Su mezcla de optimismo, recortes fiscales, desregulación y rearme acelero el desgaste sovietico: la SDI ('Guerra de las Galaxias') busco que la URSS no pudiera seguir la carrera tecnológica.\n\nCon Gorbachov nego la reduccion de arsenales (tratado INF 1987) y su frase ante el muro de Berlin se volvio icónica. Su administración marco el giro neoliberal global, aunque tambien el escandalo Irán-Contra y deficits gigantes.",
    facts: ["Fue el primer presidente divorciado en asumir el cargo.", "Sobrevivió a un intento de asesinato en 1981 (69 dias tras asumir).", "En su velorio Gorbachov dijo: 'era un rapaz libre que de verdad creo en la libertad'.", "Termino la Guerra Fria como testigo del colapso sovietico (1991)."],
    timeline: [{ year: "1981", text: "Asume con recortes fiscales y endurecimiento frente a la URSS" }, { year: "1983", text: "Anuncia la SDI; ejercito de EE.UU. en Granada" }, { year: "1986", text: "Escandalo Iran-Contra" }, { year: "1987", text: "'Derribe este muro' en la puerta de Brandeburgo" }, { year: "1989", text: "Fin de su mandato; URSS en retirada" }],
    wiki: "Ronald Reagan",
  },
  {
    id: "gorbachov", cat: "LIDERES", title: "Mijaíl Gorbachov", subtitle: "Perestroika y glasnost", dates: "1931–2022 · Líder soviético 1985–1991", region: "URSS",
    img: "/assets/wiki/leader-gorbachov.jpg",
    stats: [{ label: "Reformas", value: "Perestroika (reestructura) y glasnost (transparencia)" }, { label: "Desarme", value: "Tratados INF y START con EEUU" }, { label: "Nobel", value: "de la Paz (1990)" }, { label: "Paradoja", value: "Sus reformas aceleraron la caida de la URSS" }],
    desc: "Gorbachov intento salvar el socialismo sovietico reformandolo: perestroika para la economia, glasnost para la libertad de expresion. La apertura desato fuerzas que el control no pudo frenar: caida del muro de Berlin, revoluciones en Europa del Este y, en 1991, la disolucion de la URSS.\n\nFue el protagonista del fin de la Guerra Fria sin guerra: negoció con Reagan y Bush, retiro tropas de Afganistan y rehusó reprimir violentamente. El Nobel de la Paz de 1990 reconoció su papel; dentro de Rusia muchos lo culparon del colapso nacional.",
    facts: ["La marca de su calva esta en el icónico fotograma del muro caído.", "Sobrevivio al golpe de Agosto de 1991 confinado en Crimea.", "Fue el primer y unico presidente de la URSS (creo el cargo).", "Grabó anuncios de pizza y Louis Vuitton en su vejez para financiar su fundacion."],
    timeline: [{ year: "1985", text: "Asume como secretario general del PCUS" }, { year: "1986", text: "Chernobyl: la glasnost se vuelve necesidad" }, { year: "1987", text: "Tratado INF: elimina misiles de alcance medio" }, { year: "1989", text: "Cae el muro de Berlin sin intervencion sovietica" }, { year: "1991", text: "Disolucion de la URSS" }],
    wiki: "Mijaíl Gorbachov",
  },
  {
    id: "mandela", cat: "LIDERES", title: "Nelson Mandela", subtitle: "27 anos de celda a la presidencia", dates: "1918–2013 · Presidente 1994–1999", region: "Sudáfrica",
    img: "/assets/wiki/leader-mandela.jpg",
    stats: [{ label: "Prision", value: "27 anos (18 en Robben Island)" }, { label: "Nobel", value: "de la Paz (1993, con De Klerk)" }, { label: "Presidencia", value: "Primera electa en democracia racial (1994)" }, { label: "Modelo", value: "Comision de Verdad y Reconciliacion" }],
    desc: "Mandela fue el abogado y guerrero del CNA que paso 27 anos preso por luchar contra el apartheid. Salio en 1990 sin amargura y eligio la reconciliacion en lugar de la venganza: acordo con De Klerk el fin negociado del apartheid y evito una guerra civil anunciada.\n\nElecto presidente en 1994 en las primeras elecciones libres de la historia sudafricana, creo la Comision de Verdad y Reconciliacion y proyecto la nacion arcoiris. Dejo el poder tras un solo mandato, dando ejemplo de democracia en Africa.",
    facts: ["Rechazo la libertad condicional en 1985 si renunciaba a la lucha.", "Aprendio afrikaans en la carcel para entender al carcelero.", "El dia de su liberacion (11-2-1990) lo vio el mundo en directo.", "Vistió la camiseta de los Springboks (2003) para unir a blancos y negros."],
    timeline: [{ year: "1964", text: "Condenado a cadena perpetua en el proceso de Rivonia" }, { year: "1990", text: "Liberacion tras 27 anos" }, { year: "1993", text: "Nobel de la Paz con F.W. de Klerk" }, { year: "1994", text: "Presidente: primera eleccion sin apartheid" }, { year: "2013", text: "Muere a los 95 anos" }],
    wiki: "Nelson Mandela",
  },
  {
    id: "gandhi", cat: "LIDERES", title: "Mahatma Gandhi", subtitle: "La fuerza de la no violencia", dates: "1869–1948", region: "India",
    img: "/assets/wiki/leader-gandhi.jpg",
    stats: [{ label: "Metodo", value: "Satyagraha: resistencia sin violencia" }, { label: "Marchas legendarias", value: "Sal (1930): 385 km a pie" }, { label: "Independencia", value: "India 1947" }, { label: "Fin", value: "Asesinado por un extremista (1948)" }],
    desc: "Gandhi convirtio la desobediencia civil en arma de liberacion masiva contra el imperio britanico: boicots de tejidos y sal, ayunos, marchas de masas. Su satyagraha ('aferrarse a la verdad') desafio a un imperio con la disciplina colectiva sin armas.\n\nLidero al Congreso Nacional Indio hacia la independencia de 1947, aunque la particion con Pakistán lo destrozo: se entrego a ayunos para frenar la violencia comunal. Asesinado por un nacionalista hindu en 1948, su metodo inspiró a Martin Luther King, Mandela y movimientos del siglo XX entero.",
    facts: ["Hilo su propia ropa como protesta contra los tejidos britanicos.", "La Marcha de la Sal (1930) mostro al mundo lo absurda que era la ley de la sal.", "Nombrado 'Mahatma' (alma grande) por Tagore.", "Fue nominado al Nobel 5 veces sin obtenerlo."],
    timeline: [{ year: "1915", text: "Vuelve de Sudáfrica con el metodo satyagraha" }, { year: "1930", text: "Marcha de la Sal contra el monopolio britanico" }, { year: "1942", text: "'Quit India': salida britanica ya" }, { year: "1947", text: "Independencia y particion: India/Pakistan" }, { year: "1948", text: "Asesinato en Nueva Delhi" }],
    wiki: "Mahatma Gandhi",
  },
  {
    id: "bismarck", cat: "LIDERES", title: "Otto von Bismarck", subtitle: "El canciller de hierro", dates: "1815–1898 · Canciller 1871–1890", region: "Alemania / Prusia",
    img: "/assets/wiki/leader-bismarck.jpg",
    stats: [{ label: "Unificacion", value: "Alemania 1871 (3 guerras dirigidas)" }, { label: "Doctrina", value: "'La politica es el arte de lo posible'" }, { label: "Estado social", value: "Pionero: pension y sanidad (1880s)" }, { label: "Caída", value: "Despedido por Guillermo II (1890)" }],
    desc: "Bismarck unifico Alemania 'con sangre y hierro': dirigio tres guerras calculadas (Dinamarca 1864, Austria 1866, Francia 1870-71) para coronar a Prusia como imperio aleman en Versalles, 1871. Realista genial, tejió alianzas, engaños y equilibrios para aislar a Francia y estabilizar Europa.\n\nEn lo interior inventó el Estado de bienestar moderno (seguro sanitario, accidentes, pensiones) para desactivar a los socialistas. Su sistema de alianzas sobrevivio poco tras su despido por Guillermo II; sin su mano, el tablero cayo en 1914.",
    facts: ["Provoco deliberadamente la guerra con Francia editando un telegrama.", "Dijo: 'las grandes cuestiones se deciden con sangre y hierro'.", "Creo el primer seguro de enfermedad estatal del mundo (1883).", "Sus memorias guiaron la propaganda alemana de la Gran Guerra."],
    timeline: [{ year: "1862", text: "Discurso de 'sangre y hierro' ante el parlamento" }, { year: "1866", text: "Sadowa: Prusia expulsa a Austria de Alemania" }, { year: "1871", text: "Imperio aleman proclamado en Versalles" }, { year: "1883-89", text: "Leyes sociales pioneras" }, { year: "1890", text: "Despido por el joven kaiser Guillermo II" }],
    wiki: "Otto von Bismarck",
  },
  // ================= PARTIDOS =================
  {
    id: "democratas", cat: "PARTIDOS", title: "Partido Demócrata (EEUU)", subtitle: "El burro azul", dates: "Fundado en 1828", region: "Estados Unidos",
    img: "/assets/wiki/party-dem.jpg",
    stats: [{ label: "Antigüedad", value: "El partido activo mas antiguo del mundo" }, { label: "Sello", value: "Centro-izquierda, estado social, derechos civiles" }, { label: "Presidentes clave", value: "FDR, Kennedy, Clinton, Obama, Biden" }, { label: "Base", value: "Ciudades, minorias, jovenes, costa" }],
    desc: "El Partido Demócrata nacio con Andrew Jackson y evoluciono del partido agrario y esclavista del sur al partido del New Deal y de los derechos civiles de la era Kennedy-Johnson. Hoy defiende Estado de bienestar, regulacion ambiental, aborto legal y control de armas.\n\nSu base electoral son las grandes ciudades, las minorias etnicas, mujeres jovenes y profesionales urbanos. El burro, popularizado por caricaturas de 1828 con burla, se convirtio en emblema orgulloso del partido.",
    facts: ["Es el partido politico activo mas antiguo del planeta.", "El color azul como identificador se solidificó en TV (2000).", "FDR gano 4 elecciones con la coalicion New Deal.", "El 'Super Tuesday' puede definir su nominacion en una noche."],
    timeline: [{ year: "1828", text: "Jackson funda la tradicion demócrata moderna" }, { year: "1932", text: "FDR y la coalicion New Deal" }, { year: "1964", text: "LBJ firma la ley de derechos civiles" }, { year: "2008", text: "Obama: primer presidente afroamericano" }],
    wiki: "Partido Demócrata (Estados Unidos)",
  },
  {
    id: "republicanos", cat: "PARTIDOS", title: "Partido Republicano (EEUU)", subtitle: "El partido de Lincoln", dates: "Fundado en 1854", region: "Estados Unidos",
    img: "/assets/wiki/party-rep.jpg",
    stats: [{ label: "Origen", value: "Antiesclavista del norte (1854)" }, { label: "Sello", value: "Conservadurismo fiscal y social, libre mercado" }, { label: "Presidentes clave", value: "Lincoln, Eisenhower, Reagan, Trump" }, { label: "Base", value: "Rural, suburbios blancos, evangélicos, sur" }],
    desc: "Nacido como plataforma antiesclavista, el GOP llevo a Lincoln a la presidencia y a la guerra civil que abolió la esclavitud. Durante un siglo fue el partido de los negocios y el norte; la 'estrategia sur' desde los 60 lo convirtio en dominante en el sur conservador.\n\nHoy defiende bajas tasas, desregulación, armas, valores tradicionales y fronteras firmes. El elefante, de las caricaturas de Nast (1874), es su simbolo; el rojo su color televisivo moderno.",
    facts: ["Lincoln fue su primer presidente ganador (1860).", "GOP = 'Grand Old Party', su apodo desde los 1880.", "Reagan redefinio su coalicion con evangélicos y neoliberalismo.", "El vicepresidente presenta los votos del Colegio Electoral que el mismo podria disputar."],
    timeline: [{ year: "1860", text: "Lincoln gana y estalla la secession surena" }, { year: "1968", text: "Estrategia sur de Nixon" }, { year: "1980", text: "Reagan: la revolucion conservadora" }, { year: "2016", text: "Trump: populismo nacionalista" }],
    wiki: "Partido Republicano (Estados Unidos)",
  },
  {
    id: "laborista", cat: "PARTIDOS", title: "Partido Laborista (UK)", subtitle: "Nacido del sindicalismo", dates: "Fundado en 1900", region: "Reino Unido",
    img: "/assets/wiki/party-lab.jpg",
    stats: [{ label: "Origen", value: "Comite de Representacion Obrera (1900)" }, { label: "Sello", value: "Socialdemocracia, NHS, derechos laborales" }, { label: "Lideres clave", value: "Attlee, Wilson, Blair, Corbyn, Starmer" }, { label: "Hito", value: "Estado de bienestar 1945-51" }],
    desc: "El Partido Laborista nacio de los sindicatos para dar representacion parlamentaria a la clase obrera. Bajo Attlee (1945) construyo el NHS, nacionalizo energias y ferrocarriles y desmantelo el imperio con independencia de India.\n\nTras el 'laborismo nuevo' de Blair (1997), que gano tres elecciones con centro reformado, volvio a la izquierda con Corbyn y al centro con Starmer, que arraso en 2024. El partido esta afiliado estructuralmente a los grandes sindicatos britanicos.",
    facts: ["El NHS (1948) es su obra mas amada: sanidad gratuita universal.", "Clause IV (1918) pedía propiedad colectiva; Blair la reescribió.", "Gano 419 escaños en 1997: la mayor marea del siglo.", "El 'rojo laborista' viene del cartismo y el movimiento obrero."],
    timeline: [{ year: "1900", text: "Nace el comite que devendrá partido (1906)" }, { year: "1945", text: "Attlee: welfare state y NHS" }, { year: "1997", text: "Blair rompe 18 anos de oposicion" }, { year: "2024", text: "Starmer recupera el gobierno tras 14 anos" }],
    wiki: "Partido Laborista (Reino Unido)",
  },
  {
    id: "conservador", cat: "PARTIDOS", title: "Partido Conservador (UK)", subtitle: "Los tories", dates: "Origen en 1834 (tradición tory s. XVII)", region: "Reino Unido",
    img: "/assets/wiki/party-con.jpg",
    stats: [{ label: "Apodo", value: "Tories (del gaélico: forajidos irlandeses)" }, { label: "Sello", value: "Conservadurismo, corona, mercado" }, { label: "Lideres clave", value: "Churchill, Thatcher, Johnson" }, { label: "Hito", value: "Lidero Brexit (2016-2020)" }],
    desc: "El partido Conservador es la maquina electoral mas longeva de Occidente: de los tories jacobitas al partido de la Union y el imperio. Churchill lo lidero en la guerra; Thatcher redefinio el capitalismo britanico en los 80 con privatizaciones y victoria sobre los sindicatos.\n\nEl Brexit (2016) lo devolvio al poder bajo Johnson con mayoria arrolladora en 2019, antes de desplomarse en 2024 tras 14 anos de gobierno. Su pragmatismo camaleonico —'el partido del Estado'— lo ha mantenido vivo 190 anos.",
    facts: ["'Tory' era un insulto irlandés que asumieron con orgullo.", "Thatcher gano 3 elecciones seguidas (1979, 83, 87).", "En 1990 reemplazó a Thatcher por votación interna en solo días.", "Churchill fue conservador y liberal y conservador otra vez."],
    timeline: [{ year: "1834", text: "Peel organiza el partido moderno" }, { year: "1940", text: "Churchill: gobierno de guerra" }, { year: "1979", text: "Thatcher: giro neoliberal" }, { year: "2016", text: "Referendum del Brexit divide al partido" }, { year: "2019", text: "Johnson: mayoria de 80 escaños" }],
    wiki: "Partido Conservador (Reino Unido)",
  },
  {
    id: "cdu", cat: "PARTIDOS", title: "CDU (Alemania)", subtitle: "La fuerza de la posguerra", dates: "Fundada en 1945", region: "Alemania",
    img: "/assets/wiki/party-cdu.jpg",
    stats: [{ label: "Fundacion", value: "1945, interconfesional (protestantes y católicos)" }, { label: "Sello", value: "Democracia cristiana, economia social de mercado" }, { label: "Lideres", value: "Adenauer, Kohl, Merkel" }, { label: "Record", value: "Merkel: 16 anos de cancilleria" }],
    desc: "La Union Cristianodemocrata unifico católicos y protestantes conservadores en la Alemania de posguerra. Konrad Adenauer la llevo a la fundacion de la Republica Federal, la OTAN y el 'milagro economico' con la economia social de mercado de Erhard.\n\nHelmut Kohl ejecuto la reunificacion de 1990 y Angela Merkel gobernó 16 anos convirtiendo a la CDU en maquina electoral centrista de referencia europea. Su red de asociaciones (juventud, mujeres, empresarios) sostiene su capilaridad territorial.",
    facts: ["Fue el primer gran partido alemán interconfesional (católicos+protestantes).", "Merkel fue la primera mujer canciller y la primera de la RDA.", "Kohl firmo el tratado de reunificacion en menos de un ano.", "Su 'villa' de reflexion, la Konrad-Adenauer-Stiftung, forma elites globales."],
    timeline: [{ year: "1949", text: "Adenauer: primer canciller de la RFA" }, { year: "1982-98", text: "Era Kohl y reunificacion (1990)" }, { year: "2005", text: "Merkel asume la cancilleria" }, { year: "2021", text: "Fin de la era Merkel" }],
    wiki: "Unión Cristianodemócrata de Alemania",
  },
  {
    id: "pcc", cat: "PARTIDOS", title: "Partido Comunista Chino", subtitle: "90 millones de miembros", dates: "Fundado en 1921", region: "China",
    img: "/assets/wiki/party-pcc.jpg",
    stats: [{ label: "Miembros", value: "~98 millones (el mayor del mundo)" }, { label: "En el poder", value: "Desde 1949 (partido unico)" }, { label: "Giro economico", value: "1978: reformas de mercado de Deng" }, { label: "Estructura", value: "Politburo y comite permanente de 7" }],
    desc: "El PCC es la organizacion politica mas grande del planeta y gobierna China sin oposicion desde 1949. Mao gano la guerra civil con la campesinado; Deng Xiaoping reorientó el partido hacia el capitalismo de Estado desde 1978, multiplicando el PIB por mas de 80.\n\nBajo Xi Jinping el partido centralizo poder, controla internet, ejercito y empresas, y promueve 'nacionalismo de rejuvenecimiento'. Sus 98 millones de miembros pasan por escuelas de partido y rendicion de cuentas internas; el acceso a cargos publicos pasa por sus filas.",
    facts: ["Nacio en Shanghai con solo 12 delegados (1921).", "Su 'comite permanente' de 7 hombres decide todo en China.", "Los miembros renuevan compromiso con ceremonia y puño alzado.", "Xi Jinping elimino el limite de dos mandatos en 2018."],
    timeline: [{ year: "1921", text: "Primer congreso clandestino en Shanghai" }, { year: "1949", text: "Victoria sobre el Kuomintang" }, { year: "1978", text: "Deng: apertura economica" }, { year: "2018", text: "Xi: mandato indefinido" }],
    wiki: "Partido Comunista de China",
  },
  {
    id: "cni", cat: "PARTIDOS", title: "Congreso Nacional Indio", subtitle: "El partido de Gandhi y Nehru", dates: "Fundado en 1885", region: "India",
    img: "/assets/wiki/party-cni.jpg",
    stats: [{ label: "Fundacion", value: "1885 (partido mas viejo de Asia)" }, { label: "Lideres", value: "Gandhi (moral), Nehru, Indira, Rajiv, Sonia, Rahul" }, { label: "Sello", value: "Secularismo, no alineacion, reformas sociales" }, { label: "Hoy", value: "Principal oposicion frente al BJP" }],
    desc: "El Congreso Nacional Indio nacio como movimiento de elite educada y se convirtio, con Gandhi, en la maquina de masas de la independencia: satyagraha, boicots y la marcha de la sal. Goberno India casi sin interrupciones de 1947 a 1989 con Nehru, Indira Gandhi y Rajiv.\n\nSu legado: constitucion secular, no alineacion en la Guerra Fria, verde revolucion y reforma agraria parcial. En decadas recientes cayo frente al BJP nacionalista; la dinastia Nehru-Gandhi (sin parentesco con Mahatma) sigue marcando su vida interna.",
    facts: ["Indira Gandhi fue asesinada por sus propios guardias sij (1984).", "Su hijo Rajiv, ex-piloto, fue asesinado por un suicida tamil (1991).", "Nehru pronuncio el 'Tryst with destiny' al nacer la India libre.", "El simbolo del partido es la mano abierta."],
    timeline: [{ year: "1885", text: "Primer congreso en Bombay" }, { year: "1947", text: "Independencia con Nehru" }, { year: "1975", text: "Indira: estado de emergencia" }, { year: "2014", text: "Colapso electoral frente al BJP" }],
    wiki: "Congreso Nacional Indio",
  },
  // ================= RELIGIONES (fotos reales) =================
  {
    id: "cristianismo", cat: "RELIGIONES", title: "Cristianismo", subtitle: "La fe mas extendida", dates: "Desde el s. I d.C.", region: "Global (2.400 M de fieles)",
    img: "/assets/wiki/rel-cristianismo.jpg",
    stats: [{ label: "Fieles", value: "~2.400 millones (31% del mundo)" }, { label: "Ramas", value: "Católica, ortodoxa, protestante..." }, { label: "Texto", value: "Biblia (Antiguo y Nuevo Testamento)" }, { label: "Centro", value: "Vatican · Jerusalen como cuna" }],
    desc: "El cristianismo nace de la predicacion de Jesús de Nazaret en la Judea romana y de la creencia en su resurreccion. El imperio lo legalizo (313) y lo hizo oficial (380); desde entonces estructuró arte, derecho, calendario y moral de Occidente y se expandio por todo el planeta.\n\nSus grandes ramas —católica, ortodoxa y las iglesias de la Reforma— comparten creencia en un Dios trino, la salvacion por fe y gracia, y la Biblia como escritura. La fe mas grande del mundo hoy crece rapidísimo en Africa y Asia.",
    facts: ["La Basílica de San Pedro tardo 120 anos en terminarse.", "Los diez mandamientos estructuran legislaciones de medio mundo.", "El cisma de 1054 dividio Roma y Constantinopla.", "Hay mas cristianos en Africa que en Europa desde 2018."],
    timeline: [{ year: "313", text: "Edicto de Milan: libertad de culto" }, { year: "380", text: "Religion oficial del imperio" }, { year: "1054", text: "Gran Cisma Oriente-Occidente" }, { year: "1517", text: "Lutero clava sus tesis: Reforma protestante" }, { year: "1962", text: "Concilio Vaticano II: apertura moderna" }],
    wiki: "Cristianismo",
  },
  {
    id: "islam", cat: "RELIGIONES", title: "Islam", subtitle: "Sumision a Dios", dates: "Desde el s. VII", region: "Global (1.900 M de fieles)",
    img: "/assets/wiki/rel-islam.jpg",
    stats: [{ label: "Fieles", value: "~1.900 millones (25% del mundo)" }, { label: "Ramas", value: "Sunita (85-90%), chiita (10-15%)" }, { label: "Texto", value: "Coran · Suna del Profeta" }, { label: "Pilares", value: "5: fe, oración, limosna, ayuno, peregrinacion" }],
    desc: "El islam nace en Arabia con la revelacion de Mahoma (570-632): un solo Dios (Allah), el Coran como palabra literal y la comunidad de creyentes (umma) sobre naciones tribales. En un siglo conquisto de España a Persia; su edad de oro preservo y amplio la ciencia clasica.\n\nLos cinco pilares ordenan la vida: shahada (fe), oración cinco veces al día, zakat (limosna), ayuno de Ramadán y hach (peregrinacion a La Meca). Hoy es la religion de mas rapido crecimiento demografico del planeta.",
    facts: ["La Kaaba de La Meca recibe ~2,5 M de peregrinos al ano.", "El ano 622 (Hégira) es el ano 1 del calendario islamico.", "La Edad de Oro islamica inventó algebra, optica y hospitales modernos.", "Sunitas y chiitas se dividieron en 632 por la sucesion de Mahoma."],
    timeline: [{ year: "622", text: "Hégira: Mahoma emigra a Medina" }, { year: "632", text: "Muerte del Profeta; Coran unificado" }, { year: "750", text: "El islam llega de Espana a Asia Central" }, { year: "1258", text: "Caida de Bagdad: fin de la edad de oro" }, { year: "Hoy", text: "2a religion mundial y la de mas crecimiento" }],
    wiki: "Islam",
  },
  {
    id: "hinduismo", cat: "RELIGIONES", title: "Hinduismo", subtitle: "La religion mas antigua viva", dates: "~2300-1500 a.C. (raices)", region: "India y Nepal (1.200 M de fieles)",
    img: "/assets/wiki/rel-hinduismo.jpg",
    stats: [{ label: "Fieles", value: "~1.200 millones (15% del mundo)" }, { label: "Textos", value: "Vedas, Upanishads, Bhagavad Gita" }, { label: "Conceptos", value: "Dharma, karma, samsara, moksha" }, { label: "Dioses", value: "Brahma, Vishnu, Shiva y millones de formas" }],
    desc: "El hinduismo no tiene fundador ni un unico libro: es un oceano de tradiciones, rituales y filosofias que fluyen del valle del Indo. Sus vedas son los textos sagrados vivos mas antiguos; su vision de ciclo (samsara), karma y liberacion (moksha) estructuró la vida del subcontinente.\n\nPoliteista, monista y a la vez monoteista segun la escuela, venera a Vishnu, Shiva, Devi y millones de formas de lo divino. El Ganges es rio sagrado; Varanasi, ciudad eterna. La casta, aunque abolida legalmente, sigue condicionando sociedad y politica indias.",
    facts: ["El om (ॐ) es el sonido primordial del universo en los vedas.", "El Kumbh Mela reune a 100+ M de peregrinos: la mayor reunion humana.", "La Bhagavad Gita es un dialogo en medio de una batalla épica.", "El yoga nacio como disciplina espiritual hindu."],
    timeline: [{ year: "1500 a.C.", text: "Vedas compuestos en sanscrito" }, { year: "500 a.C.-500 d.C.", text: "Epicas: Mahabharata y Ramayana" }, { year: "1947", text: "India independiente: la dharma republicana" }, { year: "Hoy", text: "3a religion mundial; mayoritaria en India y Nepal" }],
    wiki: "Hinduismo",
  },
  {
    id: "budismo", cat: "RELIGIONES", title: "Budismo", subtitle: "El camino del medio", dates: "Desde el s. VI a.C.", region: "Asia (520 M de fieles)",
    img: "/assets/wiki/rel-budismo.jpg",
    stats: [{ label: "Fieles", value: "~520 millones (7% del mundo)" }, { label: "Fundador", value: "Siddhartha Gautama, el Buda" }, { label: "Ramas", value: "Theravada, Mahayana, Vajrayana (tibetano)" }, { label: "Nucleo", value: "4 Nobles Verdades · sendero de 8 pasos" }],
    desc: "Siddhartha Gautama, principe nepali, renuncio a palacio, alcanzo la iluminacion bajo la higuera de Bodh Gaya y enseño durante 45 anos una salida del sufrimiento: las Cuatro Nobles Verdades y el Noble Sendero Octuple. Sin dios creador, el budismo es camino etico-meditativo.\n\nSe expandio desde India por Asia: Theravada en el sudeste, Mahayana en China-Japon-Corea, Vajrayana en Tibet. Hoy medita en Silicon Valley y sobrevive al exilio tibetano con el dalai lama como simbolo global de compasion.",
    facts: ["La rueda del dharma gira en la bandera de la India.", "Los monjes tibetanos discuten filosofia con palmadas rituales.", "El budismo y la ciencia dialogan formalmente desde 1987 (Mind & Life).", "El Buda nacio principe y enseno 45 anos antes de morir en silencio."],
    timeline: [{ year: "528 a.C.", text: "Iluminacion de Buda en Bodh Gaya" }, { year: "250 a.C.", text: "Ashoka lo hace religion de estado" }, { year: "s. I d.C.", text: "Llega a China por la ruta de la seda" }, { year: "1959", text: "Exilio del dalai lama a India" }],
    wiki: "Budismo",
  },
  {
    id: "judaismo", cat: "RELIGIONES", title: "Judaismo", subtitle: "La primera fe monoteísta", dates: "~2000 a.C. (raices)", region: "Israel y diáspora (15 M de fieles)",
    img: "/assets/wiki/rel-judaismo.jpg",
    stats: [{ label: "Fieles", value: "~15 millones" }, { label: "Textos", value: "Torah, Tanaj, Talmud" }, { label: "Ramas", value: "Ortodoxa, conservadora, reformista" }, { label: "Sello", value: "Alianza, ley, memoria y esperanza" }],
    desc: "El judaismo es la religion monoteista mas antigua en continuidad: la alianza de Abraham y el exito de Egipto fundan un pueblo (Israel) cuyo destino se juega en la ley (torah), la memoria y la esperanza mesianica. Su sabiduria rabínica —el Talmud— es un océano de debate legal y ético.\n\nSiglos de diaspora forjaron comunidades de Bagdad a Brooklyn, y la tragedia del Holocausto (1941-45) segó un tercio del pueblo judio. El Estado de Israel (1948) reconfiguro su vida politica; su herencia directa ilumina al cristianismo y al islam.",
    facts: ["El muro de las lamentaciones es el ultimo resto del Templo de Jerusalén.", "El sabbat prohíbe 39 tipos de trabajo tradicionalmente enumerados.", "La Bar Mitzvah marca la mayoría de edad religiosa a los 13 anos.", "Yiddish y ladino son lenguas judias de la diaspora europea."],
    timeline: [{ year: "~1300 a.C.", text: "Exodo: tradicion de Moises y la ley" }, { year: "70 d.C.", text: "Destruccion del Templo: era rabínica" }, { year: "1492", text: "Expulsion de España: diaspora sefardi" }, { year: "1941-45", text: "Holocausto: 6 M de victimas" }, { year: "1948", text: "Fundacion de Israel" }],
    wiki: "Judaísmo",
  },
  {
    id: "sijismo", cat: "RELIGIONES", title: "Sijismo", subtitle: "Discípulos del Gurú", dates: "Fundado en 1469", region: "Panyab (30 M de fieles)",
    img: "/assets/wiki/rel-sijismo.jpg",
    stats: [{ label: "Fieles", value: "~30 millones (5a religion mundial)" }, { label: "Fundador", value: "Guru Nanak (1469-1539)" }, { label: "Texto", value: "Guru Granth Sahib (gurú viviente)" }, { label: "Simbolos", value: "5 K: kesh, kangha, kara, kachera, kirpan" }],
    desc: "Guru Nanak fundó en el Panyab una fe monoteista que rechaza castas, rituales vacios y divisiones religiosas: 'no hay hindu, no hay musulman'. Diez gurus sucesivos moldearon la comunidad (khalsa) hasta proclamar al propio libro sagrado gurú eterno.\n\nIdentidad visible (turbante y barba), templos comunitarios (gurdwara) con cocina gratuita para cualquiera (langar), y etica de trabajo, igualdad y servicio armado defensivo. Los sij han sido soldados legendarios del ejercito indio y britanico.",
    facts: ["El langar del Templo Dorado alimenta a 100.000 personas gratis al día.", "El kirpan (daga) es simbolo de justicia, no agresion.", "Los sij representan ~2% de India pero 20% de sus oficiales militares.", "El turbante sij NO es costumbre: es obligacion religiosa del khalsa."],
    timeline: [{ year: "1469", text: "Nace Guru Nanak en el Panyab" }, { year: "1699", text: "Guru Gobind Singh crea el khalsa (5 K)" }, { year: "1801", text: "Imperio sij de Ranjit Singh" }, { year: "1984", text: "Operacion Estrella Azul y crisis con India" }],
    wiki: "Sijismo",
  },
  {
    id: "taoismo", cat: "RELIGIONES", title: "Taoísmo", subtitle: "El camino del agua", dates: "Desde el s. VI a.C.", region: "China (~12 M + influencia cultural)",
    img: "/assets/wiki/rel-taoismo.jpg",
    stats: [{ label: "Texto", value: "Tao Te Ching, atribuido a Lao Tse" }, { label: "Nucleo", value: "Tao (camino), wu wei (no-forzar)" }, { label: "Simbolo", value: "Yin-yang: complementarios opuestos" }, { label: "Practicas", value: "Tai chi, feng shui, alquimia interna" }],
    desc: "El taoísmo enseña a vivir segun el Tao, el flujo innombrable del cosmos: como el agua, que cede y aun así esculpe la roca. Su saber es paradójico: no actuar es actuar (wu wei), la fuerza nace de la suavidad, el vacio es util.\n\nComo filosofia (dao jia) y religion (dao jiao) marco la medicina china, las artes marciales, la pintura de paisaje y el ideal del sabio retirado. Junto al confucianismo y el budismo formó las 'tres doctrinas' chinas, tejidas en la vida cotidiana de mil millones de personas.",
    facts: ["El Tao Te Ching es el libro traducido despues de la Biblia.", "'Wu wei' no es pereza: es accion sin friccion egoica.", "El tai chi es taoismo en movimiento: meditación en marcha.", "Los monjes de Wudang todavia mantienen artes marciales internas."],
    timeline: [{ year: "s. VI a.C.", text: "Lao Tse y el Tao Te Ching" }, { year: "s. II d.C.", text: "Escuelas religiosas organizadas" }, { year: "618-907", text: "Apogeo imperial Tang" }, { year: "Hoy", text: "Renacimiento con tai chi, qigong y feng shui global" }],
    wiki: "Taoísmo",
  },
];

