// v20 DATASET MUNDIAL REAL: 251 países/territorios con nombre en español,
// bandera real (flagcdn.com/{code}.png) y moneda oficial con tasa de cambio (fuente: open.er-api.com, captura del 2026-09-09).
// NO editar a mano: regenerar con scripts/gen-world-data.mjs.

export interface WorldFlag {
  code: string;   // ISO 3166-1 alpha-2 en minúsculas (= código de bandera en flagcdn)
  name: string;   // nombre en español
  region: string;
}

export interface WorldCountry {
  code: string;
  name: string;
  region: string;
  curCode: string;  // código ISO 4217 de la moneda
  curName: string;
  symbol: string;
  rate: number;     // unidades de moneda por 1 USD
}

export const WORLD_FLAGS: WorldFlag[] = [
  { code: "af", name: "Afganistán", region: "Asia" },
  { code: "ax", name: "Alandia", region: "Europa" },
  { code: "al", name: "Albania", region: "Europa" },
  { code: "de", name: "Alemania", region: "Europa" },
  { code: "ad", name: "Andorra", region: "Europa" },
  { code: "ao", name: "Angola", region: "África" },
  { code: "ai", name: "Anguilla", region: "América" },
  { code: "aq", name: "Antártida", region: "Antártida" },
  { code: "ag", name: "Antigua y Barbuda", region: "América" },
  { code: "sa", name: "Arabia Saudí", region: "Asia" },
  { code: "dz", name: "Argelia", region: "África" },
  { code: "ar", name: "Argentina", region: "América" },
  { code: "am", name: "Armenia", region: "Asia" },
  { code: "aw", name: "Aruba", region: "América" },
  { code: "au", name: "Australia", region: "Oceanía" },
  { code: "at", name: "Austria", region: "Europa" },
  { code: "az", name: "Azerbaiyán", region: "Asia" },
  { code: "bs", name: "Bahamas", region: "América" },
  { code: "bh", name: "Bahrein", region: "Asia" },
  { code: "bd", name: "Bangladesh", region: "Asia" },
  { code: "bb", name: "Barbados", region: "América" },
  { code: "be", name: "Bélgica", region: "Europa" },
  { code: "bz", name: "Belice", region: "América" },
  { code: "bj", name: "Benín", region: "África" },
  { code: "bm", name: "Bermudas", region: "América" },
  { code: "by", name: "Bielorrusia", region: "Europa" },
  { code: "bo", name: "Bolivia", region: "América" },
  { code: "ba", name: "Bosnia y Herzegovina", region: "Europa" },
  { code: "bw", name: "Botswana", region: "África" },
  { code: "br", name: "Brasil", region: "América" },
  { code: "bn", name: "Brunei", region: "Asia" },
  { code: "bg", name: "Bulgaria", region: "Europa" },
  { code: "bf", name: "Burkina Faso", region: "África" },
  { code: "bi", name: "Burundi", region: "África" },
  { code: "bt", name: "Bután", region: "Asia" },
  { code: "cv", name: "Cabo Verde", region: "África" },
  { code: "kh", name: "Camboya", region: "Asia" },
  { code: "cm", name: "Camerún", region: "África" },
  { code: "ca", name: "Canadá", region: "América" },
  { code: "bq", name: "Caribe Neerlandés", region: "América" },
  { code: "qa", name: "Catar", region: "Asia" },
  { code: "td", name: "Chad", region: "África" },
  { code: "cz", name: "Chequia", region: "Europa" },
  { code: "cl", name: "Chile", region: "América" },
  { code: "cn", name: "China", region: "Asia" },
  { code: "cy", name: "Chipre", region: "Europa" },
  { code: "va", name: "Ciudad del Vaticano", region: "Europa" },
  { code: "co", name: "Colombia", region: "América" },
  { code: "km", name: "Comoras", region: "África" },
  { code: "cg", name: "Congo", region: "África" },
  { code: "cd", name: "Congo (Rep. Dem.)", region: "África" },
  { code: "kp", name: "Corea del Norte", region: "Asia" },
  { code: "kr", name: "Corea del Sur", region: "Asia" },
  { code: "ci", name: "Costa de Marfil", region: "África" },
  { code: "cr", name: "Costa Rica", region: "América" },
  { code: "hr", name: "Croacia", region: "Europa" },
  { code: "cu", name: "Cuba", region: "América" },
  { code: "cw", name: "Curazao", region: "América" },
  { code: "dk", name: "Dinamarca", region: "Europa" },
  { code: "dj", name: "Djibouti", region: "África" },
  { code: "dm", name: "Dominica", region: "América" },
  { code: "ec", name: "Ecuador", region: "América" },
  { code: "eg", name: "Egipto", region: "África" },
  { code: "sv", name: "El Salvador", region: "América" },
  { code: "ae", name: "Emiratos Árabes Unidos", region: "Asia" },
  { code: "er", name: "Eritrea", region: "África" },
  { code: "sk", name: "Eslovaquia", region: "Europa" },
  { code: "si", name: "Eslovenia", region: "Europa" },
  { code: "es", name: "España", region: "Europa" },
  { code: "us", name: "Estados Unidos", region: "América" },
  { code: "ee", name: "Estonia", region: "Europa" },
  { code: "sz", name: "Esuatini", region: "África" },
  { code: "et", name: "Etiopía", region: "África" },
  { code: "ph", name: "Filipinas", region: "Asia" },
  { code: "fi", name: "Finlandia", region: "Europa" },
  { code: "fj", name: "Fiyi", region: "Oceanía" },
  { code: "fr", name: "Francia", region: "Europa" },
  { code: "ga", name: "Gabón", region: "África" },
  { code: "gm", name: "Gambia", region: "África" },
  { code: "ge", name: "Georgia", region: "Asia" },
  { code: "gh", name: "Ghana", region: "África" },
  { code: "gi", name: "Gibraltar", region: "Europa" },
  { code: "gr", name: "Grecia", region: "Europa" },
  { code: "gd", name: "Grenada", region: "América" },
  { code: "gl", name: "Groenlandia", region: "América" },
  { code: "gp", name: "Guadalupe", region: "América" },
  { code: "gu", name: "Guam", region: "Oceanía" },
  { code: "gt", name: "Guatemala", region: "América" },
  { code: "gf", name: "Guayana Francesa", region: "América" },
  { code: "gg", name: "Guernsey", region: "Europa" },
  { code: "gn", name: "Guinea", region: "África" },
  { code: "gq", name: "Guinea Ecuatorial", region: "África" },
  { code: "gw", name: "Guinea-Bisáu", region: "África" },
  { code: "gy", name: "Guyana", region: "América" },
  { code: "ht", name: "Haití", region: "América" },
  { code: "hn", name: "Honduras", region: "América" },
  { code: "hk", name: "Hong Kong", region: "Asia" },
  { code: "hu", name: "Hungría", region: "Europa" },
  { code: "in", name: "India", region: "Asia" },
  { code: "id", name: "Indonesia", region: "Asia" },
  { code: "iq", name: "Irak", region: "Asia" },
  { code: "ir", name: "Iran", region: "Asia" },
  { code: "ie", name: "Irlanda", region: "Europa" },
  { code: "bv", name: "Isla Bouvet", region: "Antártida" },
  { code: "im", name: "Isla de Man", region: "Europa" },
  { code: "cx", name: "Isla de Navidad", region: "Oceanía" },
  { code: "nf", name: "Isla de Norfolk", region: "Oceanía" },
  { code: "is", name: "Islandia", region: "Europa" },
  { code: "ky", name: "Islas Caimán", region: "América" },
  { code: "cc", name: "Islas Cocos o Islas Keeling", region: "Oceanía" },
  { code: "ck", name: "Islas Cook", region: "Oceanía" },
  { code: "fo", name: "Islas Faroe", region: "Europa" },
  { code: "gs", name: "Islas Georgias del Sur y Sandwich del Sur", region: "Antártida" },
  { code: "hm", name: "Islas Heard y McDonald", region: "Antártida" },
  { code: "fk", name: "Islas Malvinas", region: "América" },
  { code: "mp", name: "Islas Marianas del Norte", region: "Oceanía" },
  { code: "mh", name: "Islas Marshall", region: "Oceanía" },
  { code: "pn", name: "Islas Pitcairn", region: "Oceanía" },
  { code: "sb", name: "Islas Salomón", region: "Oceanía" },
  { code: "sj", name: "Islas Svalbard y Jan Mayen", region: "Europa" },
  { code: "tk", name: "Islas Tokelau", region: "Oceanía" },
  { code: "tc", name: "Islas Turks y Caicos", region: "América" },
  { code: "um", name: "Islas Ultramarinas Menores de Estados Unidos", region: "América" },
  { code: "vi", name: "Islas Vírgenes de los Estados Unidos", region: "América" },
  { code: "vg", name: "Islas Vírgenes del Reino Unido", region: "América" },
  { code: "il", name: "Israel", region: "Asia" },
  { code: "it", name: "Italia", region: "Europa" },
  { code: "jm", name: "Jamaica", region: "América" },
  { code: "jp", name: "Japón", region: "Asia" },
  { code: "je", name: "Jersey", region: "Europa" },
  { code: "jo", name: "Jordania", region: "Asia" },
  { code: "kz", name: "Kazajistán", region: "Asia" },
  { code: "ke", name: "Kenia", region: "África" },
  { code: "kg", name: "Kirguizistán", region: "Asia" },
  { code: "ki", name: "Kiribati", region: "Oceanía" },
  { code: "xk", name: "Kosovo", region: "Europa" },
  { code: "kw", name: "Kuwait", region: "Asia" },
  { code: "la", name: "Laos", region: "Asia" },
  { code: "ls", name: "Lesotho", region: "África" },
  { code: "lv", name: "Letonia", region: "Europa" },
  { code: "lb", name: "Líbano", region: "Asia" },
  { code: "lr", name: "Liberia", region: "África" },
  { code: "ly", name: "Libia", region: "África" },
  { code: "li", name: "Liechtenstein", region: "Europa" },
  { code: "lt", name: "Lituania", region: "Europa" },
  { code: "lu", name: "Luxemburgo", region: "Europa" },
  { code: "mo", name: "Macao", region: "Asia" },
  { code: "mk", name: "Macedonia del Norte", region: "Europa" },
  { code: "mg", name: "Madagascar", region: "África" },
  { code: "my", name: "Malasia", region: "Asia" },
  { code: "mw", name: "Malawi", region: "África" },
  { code: "mv", name: "Maldivas", region: "Asia" },
  { code: "ml", name: "Mali", region: "África" },
  { code: "mt", name: "Malta", region: "Europa" },
  { code: "ma", name: "Marruecos", region: "África" },
  { code: "mq", name: "Martinica", region: "América" },
  { code: "mu", name: "Mauricio", region: "África" },
  { code: "mr", name: "Mauritania", region: "África" },
  { code: "yt", name: "Mayotte", region: "África" },
  { code: "mx", name: "México", region: "América" },
  { code: "fm", name: "Micronesia", region: "Oceanía" },
  { code: "md", name: "Moldavia", region: "Europa" },
  { code: "mc", name: "Mónaco", region: "Europa" },
  { code: "mn", name: "Mongolia", region: "Asia" },
  { code: "me", name: "Montenegro", region: "Europa" },
  { code: "ms", name: "Montserrat", region: "América" },
  { code: "mz", name: "Mozambique", region: "África" },
  { code: "mm", name: "Myanmar", region: "Asia" },
  { code: "na", name: "Namibia", region: "África" },
  { code: "nr", name: "Nauru", region: "Oceanía" },
  { code: "np", name: "Nepal", region: "Asia" },
  { code: "ni", name: "Nicaragua", region: "América" },
  { code: "ne", name: "Níger", region: "África" },
  { code: "ng", name: "Nigeria", region: "África" },
  { code: "nu", name: "Niue", region: "Oceanía" },
  { code: "no", name: "Noruega", region: "Europa" },
  { code: "nc", name: "Nueva Caledonia", region: "Oceanía" },
  { code: "nz", name: "Nueva Zelanda", region: "Oceanía" },
  { code: "om", name: "Omán", region: "Asia" },
  { code: "nl", name: "Países Bajos", region: "Europa" },
  { code: "pk", name: "Pakistán", region: "Asia" },
  { code: "pw", name: "Palau", region: "Oceanía" },
  { code: "ps", name: "Palestina", region: "Asia" },
  { code: "pa", name: "Panamá", region: "América" },
  { code: "pg", name: "Papúa Nueva Guinea", region: "Oceanía" },
  { code: "py", name: "Paraguay", region: "América" },
  { code: "pe", name: "Perú", region: "América" },
  { code: "pf", name: "Polinesia Francesa", region: "Oceanía" },
  { code: "pl", name: "Polonia", region: "Europa" },
  { code: "pt", name: "Portugal", region: "Europa" },
  { code: "pr", name: "Puerto Rico", region: "América" },
  { code: "gb", name: "Reino Unido", region: "Europa" },
  { code: "cf", name: "República Centroafricana", region: "África" },
  { code: "do", name: "República Dominicana", region: "América" },
  { code: "re", name: "Reunión", region: "África" },
  { code: "rw", name: "Ruanda", region: "África" },
  { code: "ro", name: "Rumania", region: "Europa" },
  { code: "ru", name: "Rusia", region: "Europa" },
  { code: "eh", name: "Sahara Occidental", region: "África" },
  { code: "mf", name: "Saint Martin", region: "América" },
  { code: "ws", name: "Samoa", region: "Oceanía" },
  { code: "as", name: "Samoa Americana", region: "Oceanía" },
  { code: "bl", name: "San Bartolomé", region: "América" },
  { code: "kn", name: "San Cristóbal y Nieves", region: "América" },
  { code: "sm", name: "San Marino", region: "Europa" },
  { code: "pm", name: "San Pedro y Miquelón", region: "América" },
  { code: "vc", name: "San Vicente y Granadinas", region: "América" },
  { code: "sh", name: "Santa Elena, Ascensión y Tristán de Acuña", region: "África" },
  { code: "lc", name: "Santa Lucía", region: "América" },
  { code: "st", name: "Santo Tomé y Príncipe", region: "África" },
  { code: "sn", name: "Senegal", region: "África" },
  { code: "rs", name: "Serbia", region: "Europa" },
  { code: "sc", name: "Seychelles", region: "África" },
  { code: "sl", name: "Sierra Leone", region: "África" },
  { code: "sg", name: "Singapur", region: "Asia" },
  { code: "sx", name: "Sint Maarten", region: "América" },
  { code: "sy", name: "Siria", region: "Asia" },
  { code: "so", name: "Somalia", region: "África" },
  { code: "lk", name: "Sri Lanka", region: "Asia" },
  { code: "za", name: "Sudáfrica", region: "África" },
  { code: "sd", name: "Sudán", region: "África" },
  { code: "ss", name: "Sudán del Sur", region: "África" },
  { code: "se", name: "Suecia", region: "Europa" },
  { code: "ch", name: "Suiza", region: "Europa" },
  { code: "sr", name: "Surinam", region: "América" },
  { code: "th", name: "Tailandia", region: "Asia" },
  { code: "tw", name: "Taiwán", region: "Asia" },
  { code: "tz", name: "Tanzania", region: "África" },
  { code: "tj", name: "Tayikistán", region: "Asia" },
  { code: "io", name: "Territorio Británico del Océano Índico", region: "África" },
  { code: "tf", name: "Tierras Australes y Antárticas Francesas", region: "Antártida" },
  { code: "tl", name: "Timor Oriental", region: "Asia" },
  { code: "tg", name: "Togo", region: "África" },
  { code: "to", name: "Tonga", region: "Oceanía" },
  { code: "tt", name: "Trinidad y Tobago", region: "América" },
  { code: "tn", name: "Túnez", region: "África" },
  { code: "tm", name: "Turkmenistán", region: "Asia" },
  { code: "tr", name: "Turquía", region: "Asia" },
  { code: "tv", name: "Tuvalu", region: "Oceanía" },
  { code: "ua", name: "Ucrania", region: "Europa" },
  { code: "ug", name: "Uganda", region: "África" },
  { code: "eu", name: "Unión Europea", region: "Europa" },
  { code: "uy", name: "Uruguay", region: "América" },
  { code: "uz", name: "Uzbekistán", region: "Asia" },
  { code: "vu", name: "Vanuatu", region: "Oceanía" },
  { code: "ve", name: "Venezuela", region: "América" },
  { code: "vn", name: "Vietnam", region: "Asia" },
  { code: "wf", name: "Wallis y Futuna", region: "Oceanía" },
  { code: "ye", name: "Yemen", region: "Asia" },
  { code: "zm", name: "Zambia", region: "África" },
  { code: "zw", name: "Zimbabue", region: "África" },
];

export const WORLD_CURRENCIES_FULL: WorldCountry[] = [
  { code: "af", name: "Afganistán", region: "Asia", curCode: "AFN", curName: "Afgani", symbol: "؋", rate: 64.779 },
  { code: "ax", name: "Alandia", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "al", name: "Albania", region: "Europa", curCode: "ALL", curName: "Lek albanés", symbol: "L", rate: 79.3171 },
  { code: "de", name: "Alemania", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "ad", name: "Andorra", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "ao", name: "Angola", region: "África", curCode: "AOA", curName: "Kwanza", symbol: "Kz", rate: 929.1974 },
  { code: "ai", name: "Anguilla", region: "América", curCode: "XCD", curName: "Dólar del Caribe Oriental", symbol: "$", rate: 2.7 },
  { code: "ag", name: "Antigua y Barbuda", region: "América", curCode: "XCD", curName: "Dólar del Caribe Oriental", symbol: "$", rate: 2.7 },
  { code: "sa", name: "Arabia Saudí", region: "Asia", curCode: "SAR", curName: "Riyal saudita", symbol: "ر.س", rate: 3.75 },
  { code: "dz", name: "Argelia", region: "África", curCode: "DZD", curName: "Dinar argelino", symbol: "د.ج", rate: 133.1447 },
  { code: "ar", name: "Argentina", region: "América", curCode: "ARS", curName: "Peso argentino", symbol: "$", rate: 1510.1 },
  { code: "am", name: "Armenia", region: "Asia", curCode: "AMD", curName: "Dram", symbol: "֏", rate: 363.6666 },
  { code: "aw", name: "Aruba", region: "América", curCode: "AWG", curName: "Florín arubeño", symbol: "ƒ", rate: 1.79 },
  { code: "au", name: "Australia", region: "Oceanía", curCode: "AUD", curName: "Dólar australiano", symbol: "$", rate: 1.385421 },
  { code: "at", name: "Austria", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "az", name: "Azerbaiyán", region: "Asia", curCode: "AZN", curName: "Manat azerbaiyano", symbol: "₼", rate: 1.699638 },
  { code: "bs", name: "Bahamas", region: "América", curCode: "BSD", curName: "Dólar bahameño", symbol: "$", rate: 1 },
  { code: "bh", name: "Bahrein", region: "Asia", curCode: "BHD", curName: "Dinar bareiní", symbol: ".د.ب", rate: 0.376 },
  { code: "bd", name: "Bangladesh", region: "Asia", curCode: "BDT", curName: "Taka", symbol: "৳", rate: 122.8599 },
  { code: "bb", name: "Barbados", region: "América", curCode: "BBD", curName: "Dólar barbadeño", symbol: "$", rate: 2 },
  { code: "be", name: "Bélgica", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "bz", name: "Belice", region: "América", curCode: "BZD", curName: "Dólar beliceño", symbol: "$", rate: 2 },
  { code: "bj", name: "Benín", region: "África", curCode: "XOF", curName: "Franco CFA occidental", symbol: "Fr", rate: 564.2916 },
  { code: "bm", name: "Bermudas", region: "América", curCode: "BMD", curName: "Dólar bermudeño", symbol: "$", rate: 1 },
  { code: "by", name: "Bielorrusia", region: "Europa", curCode: "BYN", curName: "Rublo bielorruso", symbol: "Br", rate: 3.084359 },
  { code: "bo", name: "Bolivia", region: "América", curCode: "BOB", curName: "Boliviano", symbol: "Bs.", rate: 12.4259 },
  { code: "ba", name: "Bosnia y Herzegovina", region: "Europa", curCode: "BAM", curName: "Marco convertible", symbol: "KM", rate: 1.682516 },
  { code: "bw", name: "Botswana", region: "África", curCode: "BWP", curName: "Pula", symbol: "P", rate: 13.7836 },
  { code: "br", name: "Brasil", region: "América", curCode: "BRL", curName: "Real", symbol: "R$", rate: 5.102085 },
  { code: "bn", name: "Brunei", region: "Asia", curCode: "BND", curName: "Dólar de Brunéi", symbol: "$", rate: 1.26493 },
  { code: "bg", name: "Bulgaria", region: "Europa", curCode: "BGN", curName: "Lev búlgaro", symbol: "лв", rate: 1.682516 },
  { code: "bf", name: "Burkina Faso", region: "África", curCode: "XOF", curName: "Franco CFA occidental", symbol: "Fr", rate: 564.2916 },
  { code: "bi", name: "Burundi", region: "África", curCode: "BIF", curName: "Franco burundés", symbol: "Fr", rate: 3005.97 },
  { code: "bt", name: "Bután", region: "Asia", curCode: "BTN", curName: "Ngultrum", symbol: "Nu.", rate: 94.8318 },
  { code: "cv", name: "Cabo Verde", region: "África", curCode: "CVE", curName: "Escudo caboverdiano", symbol: "Esc", rate: 94.8562 },
  { code: "kh", name: "Camboya", region: "Asia", curCode: "KHR", curName: "Riel", symbol: "៛", rate: 4035.13 },
  { code: "cm", name: "Camerún", region: "África", curCode: "XAF", curName: "Franco CFA central", symbol: "Fr", rate: 564.2916 },
  { code: "ca", name: "Canadá", region: "América", curCode: "CAD", curName: "Dólar canadiense", symbol: "$", rate: 1.378466 },
  { code: "bq", name: "Caribe Neerlandés", region: "América", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "qa", name: "Catar", region: "Asia", curCode: "QAR", curName: "Riyal catarí", symbol: "ر.ق", rate: 3.64 },
  { code: "td", name: "Chad", region: "África", curCode: "XAF", curName: "Franco CFA central", symbol: "Fr", rate: 564.2916 },
  { code: "cz", name: "Chequia", region: "Europa", curCode: "CZK", curName: "Corona checa", symbol: "Kč", rate: 20.8173 },
  { code: "cl", name: "Chile", region: "América", curCode: "CLP", curName: "Peso chileno", symbol: "$", rate: 934.2116 },
  { code: "cn", name: "China", region: "Asia", curCode: "CNY", curName: "Yuan", symbol: "¥", rate: 6.72825 },
  { code: "cy", name: "Chipre", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "va", name: "Ciudad del Vaticano", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "co", name: "Colombia", region: "América", curCode: "COP", curName: "Peso colombiano", symbol: "$", rate: 3127.34 },
  { code: "km", name: "Comoras", region: "África", curCode: "KMF", curName: "Franco comorense", symbol: "Fr", rate: 423.2187 },
  { code: "cg", name: "Congo", region: "África", curCode: "XAF", curName: "Franco CFA central", symbol: "Fr", rate: 564.2916 },
  { code: "cd", name: "Congo (Rep. Dem.)", region: "África", curCode: "CDF", curName: "Franco congoleño", symbol: "FC", rate: 2301.64 },
  { code: "kp", name: "Corea del Norte", region: "Asia", curCode: "KPW", curName: "Won norcoreano", symbol: "₩", rate: 1 },
  { code: "kr", name: "Corea del Sur", region: "Asia", curCode: "KRW", curName: "Won", symbol: "₩", rate: 1340.86 },
  { code: "ci", name: "Costa de Marfil", region: "África", curCode: "XOF", curName: "Franco CFA occidental", symbol: "Fr", rate: 564.2916 },
  { code: "cr", name: "Costa Rica", region: "América", curCode: "CRC", curName: "Colón", symbol: "₡", rate: 453.5548 },
  { code: "hr", name: "Croacia", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "cu", name: "Cuba", region: "América", curCode: "CUC", curName: "Peso convertible cubano", symbol: "$", rate: 1 },
  { code: "cw", name: "Curazao", region: "América", curCode: "ANG", curName: "Florín antillano", symbol: "ƒ", rate: 1.79 },
  { code: "dk", name: "Dinamarca", region: "Europa", curCode: "DKK", curName: "Corona danesa", symbol: "kr", rate: 6.43479 },
  { code: "dj", name: "Djibouti", region: "África", curCode: "DJF", curName: "Franco yibutiano", symbol: "Fr", rate: 177.721 },
  { code: "dm", name: "Dominica", region: "América", curCode: "XCD", curName: "Dólar del Caribe Oriental", symbol: "$", rate: 2.7 },
  { code: "ec", name: "Ecuador", region: "América", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "eg", name: "Egipto", region: "África", curCode: "EGP", curName: "Libra egipcia", symbol: "£", rate: 51.0225 },
  { code: "sv", name: "El Salvador", region: "América", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "ae", name: "Emiratos Árabes Unidos", region: "Asia", curCode: "AED", curName: "Dirham", symbol: "د.إ", rate: 3.6725 },
  { code: "er", name: "Eritrea", region: "África", curCode: "ERN", curName: "Nakfa", symbol: "Nfk", rate: 15 },
  { code: "sk", name: "Eslovaquia", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "si", name: "Eslovenia", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "es", name: "España", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "us", name: "Estados Unidos", region: "América", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "ee", name: "Estonia", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "sz", name: "Esuatini", region: "África", curCode: "SZL", curName: "Lilangeni", symbol: "L", rate: 15.9987 },
  { code: "et", name: "Etiopía", region: "África", curCode: "ETB", curName: "Birr", symbol: "Br", rate: 161.2602 },
  { code: "ph", name: "Filipinas", region: "Asia", curCode: "PHP", curName: "Peso filipino", symbol: "₱", rate: 62.5436 },
  { code: "fi", name: "Finlandia", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "fj", name: "Fiyi", region: "Oceanía", curCode: "FJD", curName: "Dólar fiyiano", symbol: "$", rate: 2.196314 },
  { code: "fr", name: "Francia", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "ga", name: "Gabón", region: "África", curCode: "XAF", curName: "Franco CFA central", symbol: "Fr", rate: 564.2916 },
  { code: "gm", name: "Gambia", region: "África", curCode: "GMD", curName: "Dalasi", symbol: "D", rate: 74.5477 },
  { code: "ge", name: "Georgia", region: "Asia", curCode: "GEL", curName: "Lari", symbol: "₾", rate: 2.609251 },
  { code: "gh", name: "Ghana", region: "África", curCode: "GHS", curName: "Cedi", symbol: "₵", rate: 11.4074 },
  { code: "gi", name: "Gibraltar", region: "Europa", curCode: "GIP", curName: "Libra gibraltareña", symbol: "£", rate: 0.738491 },
  { code: "gr", name: "Grecia", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "gd", name: "Grenada", region: "América", curCode: "XCD", curName: "Dólar del Caribe Oriental", symbol: "$", rate: 2.7 },
  { code: "gl", name: "Groenlandia", region: "América", curCode: "DKK", curName: "Corona danesa", symbol: "kr.", rate: 6.43479 },
  { code: "gp", name: "Guadalupe", region: "América", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "gu", name: "Guam", region: "Oceanía", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "gt", name: "Guatemala", region: "América", curCode: "GTQ", curName: "Quetzal", symbol: "Q", rate: 7.637441 },
  { code: "gf", name: "Guayana Francesa", region: "América", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "gg", name: "Guernsey", region: "Europa", curCode: "GBP", curName: "Libra esterlina", symbol: "£", rate: 0.738452 },
  { code: "gn", name: "Guinea", region: "África", curCode: "GNF", curName: "Franco guineano", symbol: "Fr", rate: 8783.61 },
  { code: "gq", name: "Guinea Ecuatorial", region: "África", curCode: "XAF", curName: "Franco CFA central", symbol: "Fr", rate: 564.2916 },
  { code: "gw", name: "Guinea-Bisáu", region: "África", curCode: "XOF", curName: "Franco CFA occidental", symbol: "Fr", rate: 564.2916 },
  { code: "gy", name: "Guyana", region: "América", curCode: "GYD", curName: "Dólar guyanés", symbol: "$", rate: 209.1753 },
  { code: "ht", name: "Haití", region: "América", curCode: "HTG", curName: "Gourde", symbol: "G", rate: 130.6948 },
  { code: "hn", name: "Honduras", region: "América", curCode: "HNL", curName: "Lempira", symbol: "L", rate: 26.8274 },
  { code: "hk", name: "Hong Kong", region: "Asia", curCode: "HKD", curName: "Dólar de Hong Kong", symbol: "$", rate: 7.841292 },
  { code: "hu", name: "Hungría", region: "Europa", curCode: "HUF", curName: "Florín húngaro", symbol: "Ft", rate: 312.77 },
  { code: "in", name: "India", region: "Asia", curCode: "INR", curName: "Rupia india", symbol: "₹", rate: 94.8432 },
  { code: "id", name: "Indonesia", region: "Asia", curCode: "IDR", curName: "Rupia indonesia", symbol: "Rp", rate: 17628.62 },
  { code: "iq", name: "Irak", region: "Asia", curCode: "IQD", curName: "Dinar iraquí", symbol: "ع.د", rate: 1310.46 },
  { code: "ir", name: "Iran", region: "Asia", curCode: "IRR", curName: "Rial iraní", symbol: "﷼", rate: 1465710.76 },
  { code: "ie", name: "Irlanda", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "im", name: "Isla de Man", region: "Europa", curCode: "GBP", curName: "Libra esterlina", symbol: "£", rate: 0.738452 },
  { code: "cx", name: "Isla de Navidad", region: "Oceanía", curCode: "AUD", curName: "Dólar australiano", symbol: "$", rate: 1.385421 },
  { code: "nf", name: "Isla de Norfolk", region: "Oceanía", curCode: "AUD", curName: "Dólar australiano", symbol: "$", rate: 1.385421 },
  { code: "is", name: "Islandia", region: "Europa", curCode: "ISK", curName: "Corona islandesa", symbol: "kr", rate: 120.8179 },
  { code: "ky", name: "Islas Caimán", region: "América", curCode: "KYD", curName: "Dólar caimán", symbol: "$", rate: 0.833333 },
  { code: "cc", name: "Islas Cocos o Islas Keeling", region: "Oceanía", curCode: "AUD", curName: "Dólar australiano", symbol: "$", rate: 1.385421 },
  { code: "ck", name: "Islas Cook", region: "Oceanía", curCode: "CKD", curName: "Cook Islands dollar", symbol: "$", rate: 1 },
  { code: "fo", name: "Islas Faroe", region: "Europa", curCode: "DKK", curName: "Corona danesa", symbol: "kr", rate: 6.43479 },
  { code: "gs", name: "Islas Georgias del Sur y Sandwich del Sur", region: "Antártida", curCode: "SHP", curName: "Libra de Santa Elena", symbol: "£", rate: 0.738491 },
  { code: "fk", name: "Islas Malvinas", region: "América", curCode: "FKP", curName: "Libra malvinense", symbol: "£", rate: 0.738491 },
  { code: "mp", name: "Islas Marianas del Norte", region: "Oceanía", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "mh", name: "Islas Marshall", region: "Oceanía", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "pn", name: "Islas Pitcairn", region: "Oceanía", curCode: "NZD", curName: "Dólar neozelandés", symbol: "$", rate: 1.708006 },
  { code: "sb", name: "Islas Salomón", region: "Oceanía", curCode: "SBD", curName: "Dólar salomonense", symbol: "$", rate: 7.886091 },
  { code: "sj", name: "Islas Svalbard y Jan Mayen", region: "Europa", curCode: "NOK", curName: "Corona noruega", symbol: "kr", rate: 9.244483 },
  { code: "tk", name: "Islas Tokelau", region: "Oceanía", curCode: "NZD", curName: "Dólar neozelandés", symbol: "$", rate: 1.708006 },
  { code: "tc", name: "Islas Turks y Caicos", region: "América", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "um", name: "Islas Ultramarinas Menores de Estados Unidos", region: "América", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "vi", name: "Islas Vírgenes de los Estados Unidos", region: "América", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "vg", name: "Islas Vírgenes del Reino Unido", region: "América", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "il", name: "Israel", region: "Asia", curCode: "ILS", curName: "Séquel", symbol: "₪", rate: 3.018231 },
  { code: "it", name: "Italia", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "jm", name: "Jamaica", region: "América", curCode: "JMD", curName: "Dólar jamaicano", symbol: "$", rate: 158.3388 },
  { code: "jp", name: "Japón", region: "Asia", curCode: "JPY", curName: "Yen", symbol: "¥", rate: 153.8175 },
  { code: "je", name: "Jersey", region: "Europa", curCode: "GBP", curName: "Libra esterlina", symbol: "£", rate: 0.738452 },
  { code: "jo", name: "Jordania", region: "Asia", curCode: "JOD", curName: "Dinar jordano", symbol: "د.ا", rate: 0.709 },
  { code: "kz", name: "Kazajistán", region: "Asia", curCode: "KZT", curName: "Tenge", symbol: "₸", rate: 454.227 },
  { code: "ke", name: "Kenia", region: "África", curCode: "KES", curName: "Chelín keniano", symbol: "Sh", rate: 129.4372 },
  { code: "kg", name: "Kirguizistán", region: "Asia", curCode: "KGS", curName: "Som kirguís", symbol: "с", rate: 87.4797 },
  { code: "ki", name: "Kiribati", region: "Oceanía", curCode: "AUD", curName: "Dólar australiano", symbol: "$", rate: 1.385421 },
  { code: "xk", name: "Kosovo", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "kw", name: "Kuwait", region: "Asia", curCode: "KWD", curName: "Dinar kuwaití", symbol: "د.ك", rate: 0.308568 },
  { code: "la", name: "Laos", region: "Asia", curCode: "LAK", curName: "Kip", symbol: "₭", rate: 22211.53 },
  { code: "ls", name: "Lesotho", region: "África", curCode: "LSL", curName: "Loti", symbol: "L", rate: 15.9987 },
  { code: "lv", name: "Letonia", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "lb", name: "Líbano", region: "Asia", curCode: "LBP", curName: "Libra libanesa", symbol: "ل.ل", rate: 89500 },
  { code: "lr", name: "Liberia", region: "África", curCode: "LRD", curName: "Dólar liberiano", symbol: "$", rate: 174.9408 },
  { code: "ly", name: "Libia", region: "África", curCode: "LYD", curName: "Dinar libio", symbol: "ل.د", rate: 6.345773 },
  { code: "li", name: "Liechtenstein", region: "Europa", curCode: "CHF", curName: "Franco suizo", symbol: "Fr", rate: 0.80961 },
  { code: "lt", name: "Lituania", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "lu", name: "Luxemburgo", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "mo", name: "Macao", region: "Asia", curCode: "MOP", curName: "Pataca", symbol: "P", rate: 8.076472 },
  { code: "mk", name: "Macedonia del Norte", region: "Europa", curCode: "MKD", curName: "Denar macedonio", symbol: "den", rate: 53.1505 },
  { code: "mg", name: "Madagascar", region: "África", curCode: "MGA", curName: "Ariary", symbol: "Ar", rate: 4319.38 },
  { code: "my", name: "Malasia", region: "Asia", curCode: "MYR", curName: "Ringgit", symbol: "RM", rate: 4.061131 },
  { code: "mw", name: "Malawi", region: "África", curCode: "MWK", curName: "Kwacha malauí", symbol: "MK", rate: 1745.98 },
  { code: "mv", name: "Maldivas", region: "Asia", curCode: "MVR", curName: "Rufiyaa", symbol: ".ރ", rate: 15.4445 },
  { code: "ml", name: "Mali", region: "África", curCode: "XOF", curName: "Franco CFA occidental", symbol: "Fr", rate: 564.2916 },
  { code: "mt", name: "Malta", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "ma", name: "Marruecos", region: "África", curCode: "MAD", curName: "Dirham marroquí", symbol: "د.م.", rate: 9.387544 },
  { code: "mq", name: "Martinica", region: "América", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "mu", name: "Mauricio", region: "África", curCode: "MUR", curName: "Rupia de Mauricio", symbol: "₨", rate: 46.9595 },
  { code: "mr", name: "Mauritania", region: "África", curCode: "MRU", curName: "Uguiya", symbol: "UM", rate: 40.2107 },
  { code: "yt", name: "Mayotte", region: "África", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "mx", name: "México", region: "América", curCode: "MXN", curName: "Peso mexicano", symbol: "$", rate: 16.9252 },
  { code: "md", name: "Moldavia", region: "Europa", curCode: "MDL", curName: "Leu moldavo", symbol: "L", rate: 17.2407 },
  { code: "mc", name: "Mónaco", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "mn", name: "Mongolia", region: "Asia", curCode: "MNT", curName: "Tugrik", symbol: "₮", rate: 3620.32 },
  { code: "me", name: "Montenegro", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "ms", name: "Montserrat", region: "América", curCode: "XCD", curName: "Dólar del Caribe Oriental", symbol: "$", rate: 2.7 },
  { code: "mz", name: "Mozambique", region: "África", curCode: "MZN", curName: "Metical", symbol: "MT", rate: 63.7904 },
  { code: "mm", name: "Myanmar", region: "Asia", curCode: "MMK", curName: "Kyat", symbol: "Ks", rate: 2099.25 },
  { code: "na", name: "Namibia", region: "África", curCode: "NAD", curName: "Dólar namibio", symbol: "$", rate: 15.9987 },
  { code: "nr", name: "Nauru", region: "Oceanía", curCode: "AUD", curName: "Dólar australiano", symbol: "$", rate: 1.385421 },
  { code: "np", name: "Nepal", region: "Asia", curCode: "NPR", curName: "Rupia nepalesa", symbol: "₨", rate: 151.7308 },
  { code: "ni", name: "Nicaragua", region: "América", curCode: "NIO", curName: "Córdoba", symbol: "C$", rate: 36.7858 },
  { code: "ne", name: "Níger", region: "África", curCode: "XOF", curName: "Franco CFA occidental", symbol: "Fr", rate: 564.2916 },
  { code: "ng", name: "Nigeria", region: "África", curCode: "NGN", curName: "Naira", symbol: "₦", rate: 1322.01 },
  { code: "nu", name: "Niue", region: "Oceanía", curCode: "NZD", curName: "Dólar neozelandés", symbol: "$", rate: 1.708006 },
  { code: "no", name: "Noruega", region: "Europa", curCode: "NOK", curName: "Corona noruega", symbol: "kr", rate: 9.244483 },
  { code: "nc", name: "Nueva Caledonia", region: "Oceanía", curCode: "XPF", curName: "Franco CFP", symbol: "₣", rate: 102.6562 },
  { code: "nz", name: "Nueva Zelanda", region: "Oceanía", curCode: "NZD", curName: "Dólar neozelandés", symbol: "$", rate: 1.708006 },
  { code: "om", name: "Omán", region: "Asia", curCode: "OMR", curName: "Rial omaní", symbol: "ر.ع.", rate: 0.384497 },
  { code: "nl", name: "Países Bajos", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "pk", name: "Pakistán", region: "Asia", curCode: "PKR", curName: "Rupia pakistaní", symbol: "₨", rate: 277.5347 },
  { code: "pw", name: "Palau", region: "Oceanía", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "ps", name: "Palestina", region: "Asia", curCode: "EGP", curName: "Libra egipcia", symbol: "E£", rate: 51.0225 },
  { code: "pa", name: "Panamá", region: "América", curCode: "PAB", curName: "Balboa", symbol: "B/.", rate: 1 },
  { code: "pg", name: "Papúa Nueva Guinea", region: "Oceanía", curCode: "PGK", curName: "Kina", symbol: "K", rate: 4.432599 },
  { code: "py", name: "Paraguay", region: "América", curCode: "PYG", curName: "Guaraní", symbol: "₲", rate: 5948.42 },
  { code: "pe", name: "Perú", region: "América", curCode: "PEN", curName: "Sol peruano", symbol: "S/.", rate: 3.354324 },
  { code: "pf", name: "Polinesia Francesa", region: "Oceanía", curCode: "XPF", curName: "Franco CFP", symbol: "₣", rate: 102.6562 },
  { code: "pl", name: "Polonia", region: "Europa", curCode: "PLN", curName: "Zloty", symbol: "zł", rate: 3.711498 },
  { code: "pt", name: "Portugal", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "pr", name: "Puerto Rico", region: "América", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "gb", name: "Reino Unido", region: "Europa", curCode: "GBP", curName: "Libra esterlina", symbol: "£", rate: 0.738452 },
  { code: "cf", name: "República Centroafricana", region: "África", curCode: "XAF", curName: "Franco CFA central", symbol: "Fr", rate: 564.2916 },
  { code: "do", name: "República Dominicana", region: "América", curCode: "DOP", curName: "Peso dominicano", symbol: "$", rate: 59.1749 },
  { code: "re", name: "Reunión", region: "África", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "rw", name: "Ruanda", region: "África", curCode: "RWF", curName: "Franco ruandés", symbol: "Fr", rate: 1475.32 },
  { code: "ro", name: "Rumania", region: "Europa", curCode: "RON", curName: "Leu rumano", symbol: "lei", rate: 4.519506 },
  { code: "ru", name: "Rusia", region: "Europa", curCode: "RUB", curName: "Rublo", symbol: "₽", rate: 86.4198 },
  { code: "eh", name: "Sahara Occidental", region: "África", curCode: "DZD", curName: "Dinar argelino", symbol: "دج", rate: 133.1447 },
  { code: "mf", name: "Saint Martin", region: "América", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "ws", name: "Samoa", region: "Oceanía", curCode: "WST", curName: "Tala", symbol: "T", rate: 2.680999 },
  { code: "as", name: "Samoa Americana", region: "Oceanía", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "bl", name: "San Bartolomé", region: "América", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "kn", name: "San Cristóbal y Nieves", region: "América", curCode: "XCD", curName: "Dólar del Caribe Oriental", symbol: "$", rate: 2.7 },
  { code: "sm", name: "San Marino", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "pm", name: "San Pedro y Miquelón", region: "América", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "vc", name: "San Vicente y Granadinas", region: "América", curCode: "XCD", curName: "Dólar del Caribe Oriental", symbol: "$", rate: 2.7 },
  { code: "sh", name: "Santa Elena, Ascensión y Tristán de Acuña", region: "África", curCode: "GBP", curName: "Libra esterlina", symbol: "£", rate: 0.738452 },
  { code: "lc", name: "Santa Lucía", region: "América", curCode: "XCD", curName: "Dólar del Caribe Oriental", symbol: "$", rate: 2.7 },
  { code: "st", name: "Santo Tomé y Príncipe", region: "África", curCode: "STN", curName: "Dobra", symbol: "Db", rate: 21.0763 },
  { code: "sn", name: "Senegal", region: "África", curCode: "XOF", curName: "Franco CFA occidental", symbol: "Fr", rate: 564.2916 },
  { code: "rs", name: "Serbia", region: "Europa", curCode: "RSD", curName: "Dinar serbio", symbol: "дин.", rate: 100.9755 },
  { code: "sc", name: "Seychelles", region: "África", curCode: "SCR", curName: "Rupia de Seychelles", symbol: "₨", rate: 14.0499 },
  { code: "sl", name: "Sierra Leone", region: "África", curCode: "SLL", curName: "Leone", symbol: "Le", rate: 24709.03 },
  { code: "sg", name: "Singapur", region: "Asia", curCode: "SGD", curName: "Dólar de Singapur", symbol: "$", rate: 1.264905 },
  { code: "sx", name: "Sint Maarten", region: "América", curCode: "ANG", curName: "Florín antillano", symbol: "ƒ", rate: 1.79 },
  { code: "sy", name: "Siria", region: "Asia", curCode: "SYP", curName: "Libra siria", symbol: "£", rate: 121.7032 },
  { code: "so", name: "Somalia", region: "África", curCode: "SOS", curName: "Chelín somalí", symbol: "Sh", rate: 571.0492 },
  { code: "lk", name: "Sri Lanka", region: "Asia", curCode: "LKR", curName: "Rupia de Sri Lanka", symbol: "Rs රු", rate: 328.3108 },
  { code: "za", name: "Sudáfrica", region: "África", curCode: "ZAR", curName: "Rand", symbol: "R", rate: 16.0002 },
  { code: "sd", name: "Sudán", region: "África", curCode: "SDG", curName: "Libra sudanesa", symbol: "PT", rate: 449.2026 },
  { code: "ss", name: "Sudán del Sur", region: "África", curCode: "SSP", curName: "Libra sursudanesa", symbol: "£", rate: 5651.39 },
  { code: "se", name: "Suecia", region: "Europa", curCode: "SEK", curName: "Corona sueca", symbol: "kr", rate: 9.588953 },
  { code: "ch", name: "Suiza", region: "Europa", curCode: "CHF", curName: "Franco suizo", symbol: "Fr.", rate: 0.80961 },
  { code: "sr", name: "Surinam", region: "América", curCode: "SRD", curName: "Dólar surinamés", symbol: "$", rate: 37.9827 },
  { code: "th", name: "Tailandia", region: "Asia", curCode: "THB", curName: "Baht", symbol: "฿", rate: 32.9003 },
  { code: "tw", name: "Taiwán", region: "Asia", curCode: "TWD", curName: "Nuevo dólar taiwanés", symbol: "$", rate: 31.5009 },
  { code: "tz", name: "Tanzania", region: "África", curCode: "TZS", curName: "Chelín tanzano", symbol: "Sh", rate: 2645.42 },
  { code: "tj", name: "Tayikistán", region: "Asia", curCode: "TJS", curName: "Somoni", symbol: "ЅМ", rate: 9.232233 },
  { code: "io", name: "Territorio Británico del Océano Índico", region: "África", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "tf", name: "Tierras Australes y Antárticas Francesas", region: "Antártida", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "tl", name: "Timor Oriental", region: "Asia", curCode: "USD", curName: "Dólar estadounidense", symbol: "$", rate: 1 },
  { code: "tg", name: "Togo", region: "África", curCode: "XOF", curName: "Franco CFA occidental", symbol: "Fr", rate: 564.2916 },
  { code: "to", name: "Tonga", region: "Oceanía", curCode: "TOP", curName: "Paanga", symbol: "T$", rate: 2.364321 },
  { code: "tt", name: "Trinidad y Tobago", region: "América", curCode: "TTD", curName: "Dólar trinitario", symbol: "$", rate: 6.758109 },
  { code: "tn", name: "Túnez", region: "África", curCode: "TND", curName: "Dinar tunecino", symbol: "د.ت", rate: 2.904347 },
  { code: "tm", name: "Turkmenistán", region: "Asia", curCode: "TMT", curName: "Manat turcomano", symbol: "m", rate: 3.500047 },
  { code: "tr", name: "Turquía", region: "Asia", curCode: "TRY", curName: "Lira turca", symbol: "₺", rate: 48.4688 },
  { code: "tv", name: "Tuvalu", region: "Oceanía", curCode: "AUD", curName: "Dólar australiano", symbol: "$", rate: 1.385421 },
  { code: "ua", name: "Ucrania", region: "Europa", curCode: "UAH", curName: "Grivna", symbol: "₴", rate: 44.45 },
  { code: "ug", name: "Uganda", region: "África", curCode: "UGX", curName: "Chelín ugandés", symbol: "Sh", rate: 3744.25 },
  { code: "eu", name: "Unión Europea", region: "Europa", curCode: "EUR", curName: "Euro", symbol: "€", rate: 0.860279 },
  { code: "uy", name: "Uruguay", region: "América", curCode: "UYU", curName: "Peso uruguayo", symbol: "$", rate: 40.2355 },
  { code: "uz", name: "Uzbekistán", region: "Asia", curCode: "UZS", curName: "Som uzbeko", symbol: "so'm", rate: 11802.37 },
  { code: "vu", name: "Vanuatu", region: "Oceanía", curCode: "VUV", curName: "Vatu", symbol: "Vt", rate: 117.1762 },
  { code: "ve", name: "Venezuela", region: "América", curCode: "VES", curName: "Bolívar", symbol: "Bs.S.", rate: 820.1018 },
  { code: "vn", name: "Vietnam", region: "Asia", curCode: "VND", curName: "Dong", symbol: "₫", rate: 25932.75 },
  { code: "wf", name: "Wallis y Futuna", region: "Oceanía", curCode: "XPF", curName: "Franco CFP", symbol: "₣", rate: 102.6562 },
  { code: "ye", name: "Yemen", region: "Asia", curCode: "YER", curName: "Rial yemení", symbol: "﷼", rate: 236.9351 },
  { code: "zm", name: "Zambia", region: "África", curCode: "ZMW", curName: "Kwacha zambiano", symbol: "ZK", rate: 19.2361 },
  { code: "zw", name: "Zimbabue", region: "África", curCode: "BWP", curName: "Pula", symbol: "P", rate: 13.7836 },
];

export const WORLD_FLAG_MAP: Record<string, string> = Object.fromEntries(WORLD_FLAGS.map((f) => [f.code, f.name]));

export function countryName(code: string): string {
  if (!code) return "";
  return WORLD_FLAG_MAP[code] ?? String(code).toUpperCase();
}
