// Vanguard v17 — BANCO DE PREGUNTAS DEL DUELO DE TRIVIA (servidor :3003).
// 66 preguntas de guerra, geopolítica, historia y geografía en español.
// a = índice de la respuesta correcta (0-3).

export interface DuelQuestion {
  q: string;
  opts: [string, string, string, string];
  a: number;
  cat: string;
}

export const DUEL_QUESTIONS: DuelQuestion[] = [
  { q: "¿En qué año comenzó la Segunda Guerra Mundial?", opts: ["1935", "1939", "1941", "1943"], a: 1, cat: "GUERRAS" },
  { q: "¿Qué muro dividió una capital europea de 1961 a 1989?", opts: ["Muro de Varsovia", "Muro de Berlín", "Muro de Viena", "Muro de Praga"], a: 1, cat: "HISTORIA" },
  { q: "¿Cuál fue el detonante de la Primera Guerra Mundial?", opts: ["El hundimiento del Lusitania", "El asesinato de Francisco Fernando", "La invasión de Polonia", "La crisis de Cuba"], a: 1, cat: "GUERRAS" },
  { q: "¿Qué país lanzó la primera bomba atómica usada en guerra?", opts: ["URSS", "Reino Unido", "Estados Unidos", "China"], a: 2, cat: "GUERRAS" },
  { q: "¿Dónde se firmó el tratado que terminó la I Guerra Mundial?", opts: ["Versalles", "Westfalia", "Viena", "París"], a: 0, cat: "HISTORIA" },
  { q: "¿Qué alianza militar se fundó en 1949?", opts: ["Pacto de Varsovia", "OTAN", "ONU", "Unión Europea"], a: 1, cat: "GEOPOLÍTICA" },
  { q: "¿Cuál es el país más grande del mundo por superficie?", opts: ["China", "Canadá", "Rusia", "Estados Unidos"], a: 2, cat: "GEOGRAFÍA" },
  { q: "¿Qué crisis de 1962 llevó al mundo al borde de la guerra nuclear?", opts: ["Crisis de Berlín", "Crisis de los misiles de Cuba", "Crisis de Corea", "Crisis del Golfo"], a: 1, cat: "GUERRAS" },
  { q: "¿Qué muro histórico protegió a China durante siglos?", opts: ["La Gran Muralla", "Muralla Amarilla", "Fortaleza de Xian", "Muro de Piedra"], a: 0, cat: "GEOGRAFÍA" },
  { q: "¿En qué año cayó el Muro de Berlín?", opts: ["1985", "1987", "1989", "1991"], a: 2, cat: "HISTORIA" },
  { q: "¿Qué organización internacional se fundó en 1945 tras la II Guerra Mundial?", opts: ["OTAN", "ONU", "FMI", "OMS"], a: 1, cat: "GEOPOLÍTICA" },
  { q: "¿Cuál fue el conflicto bélico más largo del siglo XX?", opts: ["Vietnam", "Guerra Fría", "Corea", "Afganistán (URSS)"], a: 1, cat: "GUERRAS" },
  { q: "¿Qué país fue invadido por Alemania el 1 de septiembre de 1939?", opts: ["Francia", "Polonia", "Bélgica", "Noruega"], a: 1, cat: "GUERRAS" },
  { q: "¿Qué batalla de 1942-43 fue el punto de inflexión en el frente oriental?", opts: ["Batalla de Normandía", "Batalla de Stalingrado", "Batalla de Midway", "Batalla de El Alamein"], a: 1, cat: "GUERRAS" },
  { q: "¿Qué estrecho conecta el Mar Negro con el Mediterráneo?", opts: ["Estrecho de Gibraltar", "Estrecho del Bósforo", "Estrecho de Ormuz", "Estrecho de Malaca"], a: 1, cat: "GEOGRAFÍA" },
  { q: "¿Qué país tiene la mayor cantidad de armas nucleares?", opts: ["EE.UU.", "Rusia", "China", "Francia"], a: 1, cat: "GEOPOLÍTICA" },
  { q: "¿En qué año terminó la Guerra de Vietnam?", opts: ["1973", "1975", "1978", "1980"], a: 1, cat: "GUERRAS" },
  { q: "¿Qué imperio construyó el Coliseo de Roma?", opts: ["El griego", "El romano", "El cartaginés", "El persa"], a: 1, cat: "HISTORIA" },
  { q: "¿Cuál es el río más largo del mundo?", opts: ["Amazonas", "Nilo", "Yangtsé", "Misisipi"], a: 1, cat: "GEOGRAFÍA" },
  { q: "¿Qué documento limitó el poder real en Inglaterra desde 1215?", opts: ["La Carta Magna", "El Bill de Derechos", "El Acta de Unión", "El Acta de Habeas Corpus"], a: 0, cat: "HISTORIA" },
  { q: "¿Qué canal separa Asia de África?", opts: ["Canal de Panamá", "Canal de Suez", "Canal de Kiel", "Canal de Corinto"], a: 1, cat: "GEOGRAFÍA" },
  { q: "¿Qué país atacó Pearl Harbor en 1941?", opts: ["Alemania", "Italia", "Japón", "URSS"], a: 2, cat: "GUERRAS" },
  { q: "¿Cómo se llamó la operación aliada del desembarco de Normandía?", opts: ["Operación Barbarroja", "Operación Overlord", "Operación Market Garden", "Operación Torch"], a: 1, cat: "GUERRAS" },
  { q: "¿Qué país dividió Corea en dos tras 1945 junto a EE.UU.?", opts: ["Japón", "China", "URSS", "Reino Unido"], a: 2, cat: "HISTORIA" },
  { q: "¿Qué protocolo de 1925 prohibió las armas químicas tras la I Guerra Mundial?", opts: ["Tratado de Versalles", "Protocolo de Ginebra", "Pacto de Kellogg", "Tratado de Trianón"], a: 1, cat: "HISTORIA" },
  { q: "¿Cuál es el país más poblado del mundo (2024)?", opts: ["China", "India", "EE.UU.", "Indonesia"], a: 1, cat: "GEOGRAFÍA" },
  { q: "¿Qué guerra duró solo 6 días en 1967?", opts: ["Guerra de Yom Kippur", "Guerra de los Seis Días", "Guerra del Golfo", "Guerra de las Malvinas"], a: 1, cat: "GUERRAS" },
  { q: "¿Qué potencia colonial perdió la guerra de Vietnam de Indochina?", opts: ["Reino Unido", "Francia", "Países Bajos", "Portugal"], a: 1, cat: "HISTORIA" },
  { q: "¿En qué continente está el punto más alto del mundo?", opts: ["América", "Asia", "Europa", "África"], a: 1, cat: "GEOGRAFÍA" },
  { q: "¿Qué bloque económico agrupa a 27 países europeos?", opts: ["Schengen", "Unión Europea", "Eurozona", "Consejo de Europa"], a: 1, cat: "GEOPOLÍTICA" },
  { q: "¿Qué evento de 2001 cambió la seguridad mundial?", opts: ["Crisis financiera", "Atentados del 11-S", "Guerra de Irak", "Tsunami de Asia"], a: 1, cat: "ACTUALIDAD" },
  { q: "¿Qué país se anexionó Crimea en 2014?", opts: ["EE.UU.", "Rusia", "Turquía", "China"], a: 1, cat: "ACTUALIDAD" },
  { q: "¿Cuál fue la última plaga medieval que arrasó Europa?", opts: ["Viruela", "Peste Negra", "Cólera", "Tifus"], a: 1, cat: "HISTORIA" },
  { q: "¿Qué general lideró al ejército napoleónico en Waterloo?", opts: ["Napoleón Bonaparte", "Wellington", "Kutuzov", "Nelson"], a: 0, cat: "HISTORIA" },
  { q: "¿Qué país ganó la Guerra de las Malvinas de 1982?", opts: ["Argentina", "Reino Unido", "Chile", "EE.UU."], a: 1, cat: "GUERRAS" },
  { q: "¿Cuántos países tienen armas nucleares reconocidas por el TNP?", opts: ["3", "5", "7", "9"], a: 1, cat: "GEOPOLÍTICA" },
  { q: "¿Qué civilización construyó Machu Picchu?", opts: ["Mayas", "Aztecas", "Incas", "Olmecas"], a: 2, cat: "HISTORIA" },
  { q: "¿Qué océano es el más grande del planeta?", opts: ["Atlántico", "Índico", "Pacífico", "Ártico"], a: 2, cat: "GEOGRAFÍA" },
  { q: "¿Qué país fue el primero en usar gas mostaza en la IGM?", opts: ["Francia", "Alemania", "Reino Unido", "Austria"], a: 1, cat: "GUERRAS" },
  { q: "¿Qué conflicto enfrentó a Irán e Irak en los años 80?", opts: ["Guerra del Golfo", "Guerra Irán-Irak", "Guerra de Afganistán", "Guerra del Yom Kippur"], a: 1, cat: "GUERRAS" },
  { q: "¿Cuál es la capital de Japón?", opts: ["Kioto", "Osaka", "Tokio", "Nagoya"], a: 2, cat: "GEOGRAFÍA" },
  { q: "¿Qué país lidera históricamente la alianza OTAN?", opts: ["Alemania", "EE.UU.", "Francia", "Italia"], a: 1, cat: "GEOPOLÍTICA" },
  { q: "¿Qué tratado de 1968 limitó la proliferación nuclear?", opts: ["TNP", "START", "SALT", "CTBT"], a: 0, cat: "GEOPOLÍTICA" },
  { q: "¿Qué guerra terminó con la reunificación alemana?", opts: ["II Guerra Mundial", "Guerra Fría", "Guerra de Corea", "Guerra de Vietnam"], a: 1, cat: "HISTORIA" },
  { q: "¿Qué país tiene la mayor reserva de petróleo probada?", opts: ["Arabia Saudita", "Venezuela", "EE.UU.", "Rusia"], a: 1, cat: "GEOPOLÍTICA" },
  { q: "¿Qué ejército usó por primera vez los tanques en combate (1916)?", opts: ["Alemán", "Británico", "Francés", "Ruso"], a: 1, cat: "GUERRAS" },
  { q: "¿En qué ciudad firmó Alemania la rendición final ante la URSS en mayo de 1945?", opts: ["Berlín", "Reims", "Bonn", "Varsovia"], a: 0, cat: "HISTORIA" },
  { q: "¿Qué país colonial dominó India hasta 1947?", opts: ["Francia", "Portugal", "Reino Unido", "Países Bajos"], a: 2, cat: "HISTORIA" },
  { q: "¿Qué región de España tiene autonomía desde 1978 con conflicto histórico?", opts: ["Cataluña", "Andalucía", "Galicia", "Valencia"], a: 0, cat: "ACTUALIDAD" },
  { q: "¿Cuál es el desierto más grande del mundo (no polar)?", opts: ["Gobi", "Sahara", "Atacama", "Kalahari"], a: 1, cat: "GEOGRAFÍA" },
  { q: "¿Qué potencia europea se retiró de la Unión Europea en 2020?", opts: ["Francia", "Reino Unido", "Italia", "Polonia"], a: 1, cat: "ACTUALIDAD" },
  { q: "¿Qué guerra civil comenzó en 1936 y terminó en 1939?", opts: ["Guerra Civil Española", "Guerra Civil Griega", "Guerra Civil Rusa", "Guerra Civil China"], a: 0, cat: "GUERRAS" },
  { q: "¿Qué país atacó Ucrania a gran escala en febrero de 2022?", opts: ["Bielorrusia", "Rusia", "Polonia", "Turquía"], a: 1, cat: "ACTUALIDAD" },
  { q: "¿Qué civilización antigua inventó la democracia?", opts: ["Romana", "Griega", "Egipcia", "Persa"], a: 1, cat: "HISTORIA" },
  { q: "¿Cuál es el país más pequeño del mundo?", opts: ["Mónaco", "Vaticano", "Nauru", "San Marino"], a: 1, cat: "GEOGRAFÍA" },
  { q: "¿Qué conflictos enfrentaron a cristianos y musulmanes por Tierra Santa?", opts: ["Las Cruzadas", "La Reconquista", "Las Guerras Médicas", "La Guerra de los 30 Años"], a: 0, cat: "GUERRAS" },
  { q: "¿Qué país tiene más husos horarios?", opts: ["Rusia", "EE.UU.", "China", "Francia"], a: 3, cat: "GEOGRAFÍA" },
  { q: "¿Qué organización marca el índice global de terrorismo mundial?", opts: ["ONU", "OTAN", "IEP (Índice de Paz Global)", "Interpol"], a: 2, cat: "GEOPOLÍTICA" },
  { q: "¿Qué batalla naval de 1805 consolidó el dominio británico del mar?", opts: ["Trafalgar", "Aboukir", "Jutlandia", "Midway"], a: 0, cat: "GUERRAS" },
  { q: "¿Qué país africano nunca fue colonizado (además de Etiopía)?", opts: ["Egipto", "Liberia", "Marruecos", "Argelia"], a: 1, cat: "HISTORIA" },
  { q: "¿Qué puente conecta Europa con Asia en Estambul?", opts: ["Puente de la Bahía", "Puente del Bósforo", "Puente de Brooklyn", "Puente Golden Gate"], a: 1, cat: "GEOGRAFÍA" },
  { q: "¿En qué año se disolvió la Unión Soviética?", opts: ["1989", "1991", "1993", "1995"], a: 1, cat: "HISTORIA" },
  { q: "¿Qué ejército ganó la Guerra del Yom Kippur (1973)?", opts: ["Egipto", "Israel", "Siria", "Jordania"], a: 1, cat: "GUERRAS" },
  { q: "¿Qué país moderno corresponde a la antigua Persia?", opts: ["Irak", "Irán", "Turquía", "Siria"], a: 1, cat: "HISTORIA" },
  { q: "¿Qué alianza lideró los bloques del Este durante la Guerra Fría?", opts: ["OTAN", "Pacto de Varsovia", "SEATO", "CENTO"], a: 1, cat: "GEOPOLÍTICA" },
  { q: "¿Cuál es el volcán más activo de Europa?", opts: ["Vesubio", "Etna", "Santorni", "Hekla"], a: 1, cat: "GEOGRAFÍA" },
];
